#!/usr/bin/python
# -*- coding: utf-8 -*-

# CCD_T6 for simple use with numpy

import numpy as np #numpy arrays
import opt_einsum as oe
import sys


# returns a list of np.ndarrays ordered by growing rank: [energy, residual_vo, residual_vvoo, ...] except the scalars are returned as scalars.
def numpy_tenpi_ccd(nocc: int, nvir: int, F: list, V: list, T: list, type_: type = np.complex128) -> list:
    
    F1 = F[0]
    # F2 = F[1]
    # F3 = F[2]
    F4 = F[3]
    V1 = V[0]
    # V2 = V[1]
    V3 = V[2]
    # V4 = V[3]
    V5 = V[4]
    # V6 = V[5]
    V7 = V[6]
    # V8 = V[7]
    V9 = V[8]
    # T1 = T[0]
    T2 = T[1]
    
    # F1 = np.array([nocc, nocc], dtype=type_)     #       OO
    # F2 = np.array([nvir, nocc], dtype=type_)     #       VO
    # F3 = np.array([nocc, nvir], dtype=type_)     #       OV
    # F4 = np.array([nvir, nvir], dtype=type_)     #       VV
    # V1 = np.array([nocc, nocc, nocc, nocc], dtype=type_)     #       OOOO
    # V2 = np.array([nvir, nocc, nocc, nocc], dtype=type_)     #       VOOO
    # V3 = np.array([nvir, nvir, nocc, nocc], dtype=type_)     #       VVOO
    # V4 = np.array([nocc, nocc, nocc, nvir], dtype=type_)     #       OOOV
    # V5 = np.array([nvir, nocc, nocc, nvir], dtype=type_)     #       VOOV
    # V6 = np.array([nvir, nvir, nocc, nvir], dtype=type_)     #       VVOV
    # V7 = np.array([nocc, nocc, nvir, nvir], dtype=type_)     #       OOVV
    # V8 = np.array([nvir, nocc, nvir, nvir], dtype=type_)     #       VOVV
    # V9 = np.array([nvir, nvir, nvir, nvir], dtype=type_)     #       VVVV
    # T1 = np.array([nvir, nocc], dtype=type_)     #       VO
    # T2 = np.array([nvir, nvir, nocc, nocc], dtype=type_)     #       VVOO
    Z0 = np.zeros([1], dtype=type_)     #       scalar
    Z2 = np.zeros([nvir, nvir, nocc, nocc], dtype=type_)     #       VVOO
    # E1 = np.array([nocc, nocc], dtype=type_)     #       OO
    # G1 = np.array([nvir, nvir, nocc, nocc], dtype=type_)     #       VVOO
    # I1 = np.array([nvir, nvir, nocc, nocc], dtype=type_)     #       VVOO
    # J1 = np.array([nvir, nvir, nocc, nocc], dtype=type_)     #       VVOO
    # X1 = np.array([nocc, nocc, nocc, nocc], dtype=type_)     #       OOOO
    # A2 = np.array([nocc, nvir, nvir, nocc], dtype=type_)     #       OVVO
    # D2 = np.array([nvir, nvir, nocc, nocc], dtype=type_)     #       VVOO
    # E2 = np.array([nvir, nvir, nocc, nocc], dtype=type_)     #       VVOO
    # G2 = np.array([nvir, nvir], dtype=type_)     #       VV
    # I2 = np.array([nvir, nvir, nocc, nocc], dtype=type_)     #       VVOO
    
    print('    Running code generated by tenpi.   ')
    
    #Contraction 1; Tree Level  0; Scaling  4/ 4 Result_size  0/ 0
    Z0 += 0.25 * oe.contract('ijab,abij->',V7,T2, optimize='optimal')
    
    #Contraction 2; Tree Level  0; Scaling  2/ 6 Result_size  2/ 2
    Z2 += 0.5 * oe.contract('abcd,cdij->abij',V9,T2, optimize='optimal')
    
    #del V9
    
    E1 = np.zeros([nocc, nocc], dtype=type_)
    
    #Contraction 3; Tree Level  3; Scaling  4/ 4 Result_size  2/ 0
    E1 += oe.contract('klcd,cdlj->kj',V7,T2, optimize='optimal')
    
    G1 = np.zeros([nvir, nvir, nocc, nocc], dtype=type_)
    
    #Contraction 4; Tree Level  2; Scaling  4/ 2 Result_size  2/ 2
    G1 += oe.contract('abik,kj->abij',T2,E1, optimize='optimal')
    
    del E1
    
    #Contraction 5; Tree Level  1; Scaling  2/ 2 Result_size  2/ 2
    Z2 += 0.5 * oe.contract('abij->abij',G1)
    
    #Contraction 6; Tree Level  1; Scaling  2/ 2 Result_size  2/ 2
    Z2 += -0.5 * oe.contract('abji->abij',G1)
    
    del G1
    
    I1 = np.zeros([nvir, nvir, nocc, nocc], dtype=type_)
    
    #Contraction 7; Tree Level  2; Scaling  4/ 4 Result_size  2/ 2
    I1 += oe.contract('akic,bcjk->abij',V5,T2, optimize='optimal')
    
    #del V5
    
    #Contraction 8; Tree Level  1; Scaling  2/ 2 Result_size  2/ 2
    Z2 += oe.contract('abij->abij',I1)
    
    #Contraction 9; Tree Level  1; Scaling  2/ 2 Result_size  2/ 2
    Z2 += -1.0 * oe.contract('baij->abij',I1)
    
    #Contraction 10; Tree Level  1; Scaling  2/ 2 Result_size  2/ 2
    Z2 += -1.0 * oe.contract('abji->abij',I1)
    
    #Contraction 11; Tree Level  1; Scaling  2/ 2 Result_size  2/ 2
    Z2 += oe.contract('baji->abij',I1)
    
    del I1
    
    J1 = np.zeros([nvir, nvir, nocc, nocc], dtype=type_)
    
    #Contraction 12; Tree Level  2; Scaling  4/ 2 Result_size  2/ 2
    J1 += oe.contract('ki,bajk->baij',F1,T2, optimize='optimal')
    
    #del F1
    
    #Contraction 13; Tree Level  1; Scaling  2/ 2 Result_size  2/ 2
    Z2 += -1.0 * oe.contract('baij->abij',J1)
    
    #Contraction 14; Tree Level  1; Scaling  2/ 2 Result_size  2/ 2
    Z2 += oe.contract('baji->abij',J1)
    
    del J1
    
    X1 = np.zeros([nocc, nocc, nocc, nocc], dtype=type_)
    
    #Contraction 15; Tree Level  2; Scaling  4/ 4 Result_size  4/ 0
    X1 += oe.contract('klcd,cdij->klij',V7,T2, optimize='optimal')
    
    #Contraction 16; Tree Level  2; Scaling  4/ 0 Result_size  4/ 0
    X1 += 2.0 * oe.contract('klij->klij',V1)
    
    #del V1
    
    #Contraction 17; Tree Level  1; Scaling  6/ 2 Result_size  2/ 2
    Z2 += 0.25 * oe.contract('abkl,klij->abij',T2,X1, optimize='optimal')
    
    del X1
    
    A2 = np.zeros([nocc, nvir, nvir, nocc], dtype=type_)
    
    #Contraction 18; Tree Level  3; Scaling  4/ 4 Result_size  2/ 2
    A2 += oe.contract('klcd,dblj->kbcj',V7,T2, optimize='optimal')
    
    D2 = np.zeros([nvir, nvir, nocc, nocc], dtype=type_)
    
    #Contraction 19; Tree Level  2; Scaling  4/ 4 Result_size  2/ 2
    D2 += oe.contract('acik,kbcj->abij',T2,A2, optimize='optimal')
    
    del A2
    
    #Contraction 20; Tree Level  1; Scaling  2/ 2 Result_size  2/ 2
    Z2 += 0.5 * oe.contract('abij->abij',D2)
    
    #Contraction 21; Tree Level  1; Scaling  2/ 2 Result_size  2/ 2
    Z2 += -0.5 * oe.contract('baij->abij',D2)
    
    #Contraction 22; Tree Level  1; Scaling  2/ 2 Result_size  2/ 2
    Z2 += -0.5 * oe.contract('abji->abij',D2)
    
    #Contraction 23; Tree Level  1; Scaling  2/ 2 Result_size  2/ 2
    Z2 += 0.5 * oe.contract('baji->abij',D2)
    
    del D2
    
    E2 = np.zeros([nvir, nvir, nocc, nocc], dtype=type_)
    
    #Contraction 24; Tree Level  2; Scaling  2/ 4 Result_size  2/ 2
    E2 += oe.contract('ac,bcji->abji',F4,T2, optimize='optimal')
    
    #del F4
    
    #Contraction 25; Tree Level  1; Scaling  2/ 2 Result_size  2/ 2
    Z2 += oe.contract('abji->abij',E2)
    
    #Contraction 26; Tree Level  1; Scaling  2/ 2 Result_size  2/ 2
    Z2 += -1.0 * oe.contract('baji->abij',E2)
    
    del E2
    
    G2 = np.zeros([nvir, nvir], dtype=type_)
    
    #Contraction 27; Tree Level  3; Scaling  4/ 4 Result_size  0/ 2
    G2 += oe.contract('klcd,dbkl->bc',V7,T2, optimize='optimal')
    
    #del V7
    
    I2 = np.zeros([nvir, nvir, nocc, nocc], dtype=type_)
    
    #Contraction 28; Tree Level  2; Scaling  2/ 4 Result_size  2/ 2
    I2 += oe.contract('acij,bc->abij',T2,G2, optimize='optimal')
    
    del G2
    
    #del T2
    
    #Contraction 29; Tree Level  1; Scaling  2/ 2 Result_size  2/ 2
    Z2 += 0.5 * oe.contract('abij->abij',I2)
    
    #Contraction 30; Tree Level  1; Scaling  2/ 2 Result_size  2/ 2
    Z2 += -0.5 * oe.contract('baij->abij',I2)
    
    del I2
    
    #Contraction 31; Tree Level  1; Scaling  2/ 2 Result_size  2/ 2
    Z2 += oe.contract('abij->abij',V3)
    
    #del V3
    
    return([Z0[0], Z2])
    
# end of numpy_tenpi_ccd
