!
! CCD_T6 generated by Jan Brandejs.
!

#if (defined (VAR_MPI) && !defined(EXA_TALSH_ONLY))

subroutine exatensor_tenpi_ccd(nocc_id,nvir_id,nocc_root,nvir_root,F1,F4,T2,V1,V7, &
        V5,V3,V9,Z0,Z2)
    
    use exatensor
    use, intrinsic:: ISO_C_BINDING
    
    implicit none
    
    complex(8), parameter :: ZERO=(0.D0,0.D0),ONE_HALF=(0.5D0,0.D0), &
                             MINUS_ONE=(-1.D0,0.D0),ONE=(1.0D0,0.D0), MINUS_ONE_HALF=(-0.5D0,0.D0), &
                             MINUS_ONE_QUARTER=(-0.25D0,0.D0), ONE_QUARTER=(0.25D0,0.D0), &
                             MINUS_ONE_EIGHT=(-0.125D0,0.D0)
    
    
    integer :: ierr
    type(tens_rcrsv_t) :: one_tensor
    integer(INTD), intent(in) :: nocc_id
    integer(INTL), intent(in) :: nocc_root
    integer(INTD), intent(in) :: nvir_id
    integer(INTL), intent(in) :: nvir_root
    integer(INTD), allocatable :: tens_id(:)
    integer(INTL), allocatable :: tens_root(:)
    type(tens_rcrsv_t), intent(inout) :: F1    !       OO
    type(tens_rcrsv_t), intent(inout) :: F4    !       VV
    type(tens_rcrsv_t), intent(inout) :: T2    !       VVOO
    type(tens_rcrsv_t), intent(inout) :: V1    !       OOOO
    type(tens_rcrsv_t), intent(inout) :: V7    !       OOVV
    type(tens_rcrsv_t), intent(inout) :: V5    !       VOOV
    type(tens_rcrsv_t), intent(inout) :: V3    !       VVOO
    type(tens_rcrsv_t), intent(inout) :: V9    !       VVVV
    type(tens_rcrsv_t), intent(inout) :: Z0    !       UnitTensor
    type(tens_rcrsv_t), intent(inout) :: Z2    !       VVOO
    type(tens_rcrsv_t) :: E1    !       OO
    type(tens_rcrsv_t) :: G1    !       VVOO
    type(tens_rcrsv_t) :: I1    !       VVOO
    type(tens_rcrsv_t) :: J1    !       VVOO
    type(tens_rcrsv_t) :: X1    !       OOOO
    type(tens_rcrsv_t) :: A2    !       OVVO
    type(tens_rcrsv_t) :: D2    !       VVOO
    type(tens_rcrsv_t) :: E2    !       VVOO
    type(tens_rcrsv_t) :: G2    !       VV
    type(tens_rcrsv_t) :: I2    !       VVOO
    
    write(*,*) "    Running code generated by tenpi.   "
    
    ! one_tensor scalar is just a workaround that replaces exatensor's problematic addition by a contraction
    ierr=exatns_tensor_create(one_tensor,"autokern_one_tensor",EXA_DATA_KIND_C8)
    ierr=exatns_tensor_init(one_tensor,ONE)
    
    !Diagram      0; Contraction 1; Tree Level  0; Scaling  4/ 4/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  0/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z0()+=V7(m1,n1,e1,f1)*T2(e1,f1,m1,n1)", &
    Z0,V7,T2,prefactor=(2.5d-1,0.0d0))
    
    !Diagram      0; Contraction 2; Tree Level  0; Scaling  2/ 6/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=V9(e1,f1,d1,e2)*T2(d1,e2,m1,n1)", &
    Z2,V9,T2,prefactor=(5.0d-1,0.0d0))
    
    !ierr=exatns_tensor_destroy(V9)
    
    allocate(tens_id(2), tens_root(2))
    tens_id   = (/nocc_id,nocc_id/)
    tens_root   = (/nocc_root,nocc_root/)
    ierr=exatns_tensor_create(E1,"E1",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(E1,'ZERO')
    
    !Diagram      0; Contraction 3; Tree Level  3; Scaling  4/ 4/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("E1(l1,n1)+=V7(l1,m2,d1,e2)*T2(d1,e2,m2,n1)", &
    E1,V7,T2,prefactor=(1.0d0,0.0d0))
    
    allocate(tens_id(4), tens_root(4))
    tens_id   = (/nvir_id,nvir_id,nocc_id,nocc_id/)
    tens_root   = (/nvir_root,nvir_root,nocc_root,nocc_root/)
    ierr=exatns_tensor_create(G1,"G1",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(G1,'ZERO')
    
    !Diagram      0; Contraction 4; Tree Level  2; Scaling  4/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("G1(e1,f1,m1,n1)+=T2(e1,f1,m1,l1)*E1(l1,n1)", &
    G1,T2,E1,prefactor=(1.0d0,0.0d0))
    
    ierr=exatns_tensor_destroy(E1)
    
    !Diagram      0; Contraction 5; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=G1(e1,f1,m1,n1)*O01()", &
    Z2,G1,one_tensor,prefactor=(5.0d-1,0.0d0))
    
    !Diagram      0; Contraction 6; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=G1(e1,f1,n1,m1)*O01()", &
    Z2,G1,one_tensor,prefactor=(-5.0d-1,0.0d0))
    
    ierr=exatns_tensor_destroy(G1)
    
    allocate(tens_id(4), tens_root(4))
    tens_id   = (/nvir_id,nvir_id,nocc_id,nocc_id/)
    tens_root   = (/nvir_root,nvir_root,nocc_root,nocc_root/)
    ierr=exatns_tensor_create(I1,"I1",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(I1,'ZERO')
    
    !Diagram      0; Contraction 7; Tree Level  2; Scaling  4/ 4/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("I1(e1,f1,m1,n1)+=V5(e1,l1,m1,d1)*T2(f1,d1,n1,l1)", &
    I1,V5,T2,prefactor=(1.0d0,0.0d0))
    
    !ierr=exatns_tensor_destroy(V5)
    
    !Diagram      0; Contraction 8; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=I1(e1,f1,m1,n1)*O01()", &
    Z2,I1,one_tensor,prefactor=(1.0d0,0.0d0))
    
    !Diagram      0; Contraction 9; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=I1(f1,e1,m1,n1)*O01()", &
    Z2,I1,one_tensor,prefactor=(-1.0d0,0.0d0))
    
    !Diagram      0; Contraction 10; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=I1(e1,f1,n1,m1)*O01()", &
    Z2,I1,one_tensor,prefactor=(-1.0d0,0.0d0))
    
    !Diagram      0; Contraction 11; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=I1(f1,e1,n1,m1)*O01()", &
    Z2,I1,one_tensor,prefactor=(1.0d0,0.0d0))
    
    ierr=exatns_tensor_destroy(I1)
    
    allocate(tens_id(4), tens_root(4))
    tens_id   = (/nvir_id,nvir_id,nocc_id,nocc_id/)
    tens_root   = (/nvir_root,nvir_root,nocc_root,nocc_root/)
    ierr=exatns_tensor_create(J1,"J1",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(J1,'ZERO')
    
    !Diagram      0; Contraction 12; Tree Level  2; Scaling  4/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("J1(f1,e1,m1,n1)+=F1(l1,m1)*T2(f1,e1,n1,l1)", &
    J1,F1,T2,prefactor=(1.0d0,0.0d0))
    
    !ierr=exatns_tensor_destroy(F1)
    
    !Diagram      0; Contraction 13; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=J1(f1,e1,m1,n1)*O01()", &
    Z2,J1,one_tensor,prefactor=(-1.0d0,0.0d0))
    
    !Diagram      0; Contraction 14; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=J1(f1,e1,n1,m1)*O01()", &
    Z2,J1,one_tensor,prefactor=(1.0d0,0.0d0))
    
    ierr=exatns_tensor_destroy(J1)
    
    allocate(tens_id(4), tens_root(4))
    tens_id   = (/nocc_id,nocc_id,nocc_id,nocc_id/)
    tens_root   = (/nocc_root,nocc_root,nocc_root,nocc_root/)
    ierr=exatns_tensor_create(X1,"X1",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(X1,'ZERO')
    
    !Diagram      0; Contraction 15; Tree Level  2; Scaling  4/ 4/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  4/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("X1(l1,m2,m1,n1)+=V7(l1,m2,d1,e2)*T2(d1,e2,m1,n1)", &
    X1,V7,T2,prefactor=(1.0d0,0.0d0))
    
    !Diagram      0; Contraction 16; Tree Level  2; Scaling  4/ 0/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  4/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("X1(l1,m2,m1,n1)+=V1(l1,m2,m1,n1)*O01()", &
    X1,V1,one_tensor,prefactor=(2.0d0,0.0d0))
    
    !ierr=exatns_tensor_destroy(V1)
    
    !Diagram      0; Contraction 17; Tree Level  1; Scaling  6/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=T2(e1,f1,l1,m2)*X1(l1,m2,m1,n1)", &
    Z2,T2,X1,prefactor=(2.5d-1,0.0d0))
    
    ierr=exatns_tensor_destroy(X1)
    
    allocate(tens_id(4), tens_root(4))
    tens_id   = (/nocc_id,nvir_id,nvir_id,nocc_id/)
    tens_root   = (/nocc_root,nvir_root,nvir_root,nocc_root/)
    ierr=exatns_tensor_create(A2,"A2",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(A2,'ZERO')
    
    !Diagram      0; Contraction 18; Tree Level  3; Scaling  4/ 4/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("A2(l1,f1,d1,n1)+=V7(l1,m2,d1,e2)*T2(e2,f1,m2,n1)", &
    A2,V7,T2,prefactor=(1.0d0,0.0d0))
    
    allocate(tens_id(4), tens_root(4))
    tens_id   = (/nvir_id,nvir_id,nocc_id,nocc_id/)
    tens_root   = (/nvir_root,nvir_root,nocc_root,nocc_root/)
    ierr=exatns_tensor_create(D2,"D2",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(D2,'ZERO')
    
    !Diagram      0; Contraction 19; Tree Level  2; Scaling  4/ 4/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("D2(e1,f1,m1,n1)+=T2(e1,d1,m1,l1)*A2(l1,f1,d1,n1)", &
    D2,T2,A2,prefactor=(1.0d0,0.0d0))
    
    ierr=exatns_tensor_destroy(A2)
    
    !Diagram      0; Contraction 20; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=D2(e1,f1,m1,n1)*O01()", &
    Z2,D2,one_tensor,prefactor=(5.0d-1,0.0d0))
    
    !Diagram      0; Contraction 21; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=D2(f1,e1,m1,n1)*O01()", &
    Z2,D2,one_tensor,prefactor=(-5.0d-1,0.0d0))
    
    !Diagram      0; Contraction 22; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=D2(e1,f1,n1,m1)*O01()", &
    Z2,D2,one_tensor,prefactor=(-5.0d-1,0.0d0))
    
    !Diagram      0; Contraction 23; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=D2(f1,e1,n1,m1)*O01()", &
    Z2,D2,one_tensor,prefactor=(5.0d-1,0.0d0))
    
    ierr=exatns_tensor_destroy(D2)
    
    allocate(tens_id(4), tens_root(4))
    tens_id   = (/nvir_id,nvir_id,nocc_id,nocc_id/)
    tens_root   = (/nvir_root,nvir_root,nocc_root,nocc_root/)
    ierr=exatns_tensor_create(E2,"E2",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(E2,'ZERO')
    
    !Diagram      0; Contraction 24; Tree Level  2; Scaling  2/ 4/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("E2(e1,f1,n1,m1)+=F4(e1,d1)*T2(f1,d1,n1,m1)", &
    E2,F4,T2,prefactor=(1.0d0,0.0d0))
    
    !ierr=exatns_tensor_destroy(F4)
    
    !Diagram      0; Contraction 25; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=E2(e1,f1,n1,m1)*O01()", &
    Z2,E2,one_tensor,prefactor=(1.0d0,0.0d0))
    
    !Diagram      0; Contraction 26; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=E2(f1,e1,n1,m1)*O01()", &
    Z2,E2,one_tensor,prefactor=(-1.0d0,0.0d0))
    
    ierr=exatns_tensor_destroy(E2)
    
    allocate(tens_id(2), tens_root(2))
    tens_id   = (/nvir_id,nvir_id/)
    tens_root   = (/nvir_root,nvir_root/)
    ierr=exatns_tensor_create(G2,"G2",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(G2,'ZERO')
    
    !Diagram      0; Contraction 27; Tree Level  3; Scaling  4/ 4/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  0/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("G2(f1,d1)+=V7(l1,m2,d1,e2)*T2(e2,f1,l1,m2)", &
    G2,V7,T2,prefactor=(1.0d0,0.0d0))
    
    !ierr=exatns_tensor_destroy(V7)
    
    allocate(tens_id(4), tens_root(4))
    tens_id   = (/nvir_id,nvir_id,nocc_id,nocc_id/)
    tens_root   = (/nvir_root,nvir_root,nocc_root,nocc_root/)
    ierr=exatns_tensor_create(I2,"I2",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(I2,'ZERO')
    
    !Diagram      0; Contraction 28; Tree Level  2; Scaling  2/ 4/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("I2(e1,f1,m1,n1)+=T2(e1,d1,m1,n1)*G2(f1,d1)", &
    I2,T2,G2,prefactor=(1.0d0,0.0d0))
    
    ierr=exatns_tensor_destroy(G2)
    
    !ierr=exatns_tensor_destroy(T2)
    
    !Diagram      0; Contraction 29; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=I2(e1,f1,m1,n1)*O01()", &
    Z2,I2,one_tensor,prefactor=(5.0d-1,0.0d0))
    
    !Diagram      0; Contraction 30; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=I2(f1,e1,m1,n1)*O01()", &
    Z2,I2,one_tensor,prefactor=(-5.0d-1,0.0d0))
    
    ierr=exatns_tensor_destroy(I2)
    
    !Diagram      0; Contraction 31; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=V3(e1,f1,m1,n1)*O01()", &
    Z2,V3,one_tensor,prefactor=(1.0d0,0.0d0))
    
    !ierr=exatns_tensor_destroy(V3)
    
    
    ierr=exatns_tensor_destroy(one_tensor)
    
end subroutine exatensor_tenpi_ccd
#endif
