!
! CCSD_T6 generated by Jan Brandejs.
!

#if (defined (VAR_MPI) && !defined(EXA_TALSH_ONLY))

subroutine exatensor_tenpi_ccsd(nocc_id,nvir_id,nocc_root,nvir_root,F1,F3,F2,F4,T1, &
        T2,V1,V4,V7,V2,V5,V8,V3,V6,V9, &
        Z0,Z1,Z2)
    
    use exatensor
    use, intrinsic:: ISO_C_BINDING
    
    implicit none
    
    complex(8), parameter :: ZERO=(0.D0,0.D0),ONE_HALF=(0.5D0,0.D0), &
                             MINUS_ONE=(-1.D0,0.D0),ONE=(1.0D0,0.D0), MINUS_ONE_HALF=(-0.5D0,0.D0), &
                             MINUS_ONE_QUARTER=(-0.25D0,0.D0), ONE_QUARTER=(0.25D0,0.D0), &
                             MINUS_ONE_EIGHT=(-0.125D0,0.D0)
    
    
    integer :: ierr
    type(tens_rcrsv_t) :: one_tensor
    integer(INTD), intent(in) :: nocc_id
    integer(INTL), intent(in) :: nocc_root
    integer(INTD), intent(in) :: nvir_id
    integer(INTL), intent(in) :: nvir_root
    integer(INTD), allocatable :: tens_id(:)
    integer(INTL), allocatable :: tens_root(:)
    type(tens_rcrsv_t), intent(inout) :: F1    !       OO
    type(tens_rcrsv_t), intent(inout) :: F3    !       OV
    type(tens_rcrsv_t), intent(inout) :: F2    !       VO
    type(tens_rcrsv_t), intent(inout) :: F4    !       VV
    type(tens_rcrsv_t), intent(inout) :: T1    !       VO
    type(tens_rcrsv_t), intent(inout) :: T2    !       VVOO
    type(tens_rcrsv_t), intent(inout) :: V1    !       OOOO
    type(tens_rcrsv_t), intent(inout) :: V4    !       OOOV
    type(tens_rcrsv_t), intent(inout) :: V7    !       OOVV
    type(tens_rcrsv_t), intent(inout) :: V2    !       VOOO
    type(tens_rcrsv_t), intent(inout) :: V5    !       VOOV
    type(tens_rcrsv_t), intent(inout) :: V8    !       VOVV
    type(tens_rcrsv_t), intent(inout) :: V3    !       VVOO
    type(tens_rcrsv_t), intent(inout) :: V6    !       VVOV
    type(tens_rcrsv_t), intent(inout) :: V9    !       VVVV
    type(tens_rcrsv_t), intent(inout) :: Z0    !       UnitTensor
    type(tens_rcrsv_t), intent(inout) :: Z1    !       VO
    type(tens_rcrsv_t), intent(inout) :: Z2    !       VVOO
    type(tens_rcrsv_t) :: E1    !       OV
    type(tens_rcrsv_t) :: J1    !       OVVO
    type(tens_rcrsv_t) :: M1    !       OVVO
    type(tens_rcrsv_t) :: X1    !       OOVO
    type(tens_rcrsv_t) :: A2    !       OO
    type(tens_rcrsv_t) :: I3    !       VV
    type(tens_rcrsv_t) :: E2    !       OOVO
    type(tens_rcrsv_t) :: G2    !       OO
    type(tens_rcrsv_t) :: A3    !       OO
    type(tens_rcrsv_t) :: E3    !       VV
    type(tens_rcrsv_t) :: M3    !       OOOO
    type(tens_rcrsv_t) :: X3    !       OOOO
    type(tens_rcrsv_t) :: Y3    !       OV
    type(tens_rcrsv_t) :: A4    !       VVOO
    type(tens_rcrsv_t) :: D4    !       VVOO
    type(tens_rcrsv_t) :: E4    !       VOVO
    type(tens_rcrsv_t) :: G4    !       VOOO
    type(tens_rcrsv_t) :: I4    !       VVOO
    type(tens_rcrsv_t) :: J4    !       VOOO
    type(tens_rcrsv_t) :: M4    !       VOVO
    type(tens_rcrsv_t) :: X4    !       VOOO
    type(tens_rcrsv_t) :: Y4    !       VVOO
    type(tens_rcrsv_t) :: M6    !       OOOO
    type(tens_rcrsv_t) :: D5    !       VV
    type(tens_rcrsv_t) :: E5    !       VVOO
    type(tens_rcrsv_t) :: G5    !       VVOO
    type(tens_rcrsv_t) :: I5    !       VOOO
    type(tens_rcrsv_t) :: J5    !       OVOO
    type(tens_rcrsv_t) :: M5    !       VVVO
    type(tens_rcrsv_t) :: X5    !       VVOO
    type(tens_rcrsv_t) :: Y5    !       VVOO
    type(tens_rcrsv_t) :: A6    !       OOOO
    type(tens_rcrsv_t) :: X10    !       OOOO
    type(tens_rcrsv_t) :: A11    !       OOOO
    type(tens_rcrsv_t) :: X6    !       OVOO
    type(tens_rcrsv_t) :: E10    !       VOOO
    type(tens_rcrsv_t) :: A7    !       VVOO
    type(tens_rcrsv_t) :: M11    !       VOOO
    type(tens_rcrsv_t) :: G7    !       VVOO
    type(tens_rcrsv_t) :: J7    !       OO
    type(tens_rcrsv_t) :: M7    !       VVOO
    type(tens_rcrsv_t) :: X7    !       VVOO
    type(tens_rcrsv_t) :: Y7    !       OO
    type(tens_rcrsv_t) :: A8    !       VVOO
    type(tens_rcrsv_t) :: D8    !       OOOO
    type(tens_rcrsv_t) :: J8    !       VOOO
    type(tens_rcrsv_t) :: I10    !       OOOO
    
    write(*,*) "    Running code generated by tenpi.   "
    
    ! one_tensor scalar is just a workaround that replaces exatensor's problematic addition by a contraction
    ierr=exatns_tensor_create(one_tensor,"autokern_one_tensor",EXA_DATA_KIND_C8)
    ierr=exatns_tensor_init(one_tensor,ONE)
    
    !Diagram      0; Contraction 1; Tree Level  0; Scaling  4/ 4/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  0/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z0()+=V7(m1,n1,e1,f1)*T2(e1,f1,m1,n1)", &
    Z0,V7,T2,prefactor=(2.5d-1,0.0d0))
    
    allocate(tens_id(2), tens_root(2))
    tens_id   = (/nocc_id,nvir_id/)
    tens_root   = (/nocc_root,nvir_root/)
    ierr=exatns_tensor_create(E1,"E1",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(E1,'ZERO')
    
    !Diagram      0; Contraction 2; Tree Level  2; Scaling  3/ 3/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  1/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("E1(n1,f1)+=V7(m1,n1,e1,f1)*T1(e1,m1)", &
    E1,V7,T1,prefactor=(1.0d0,0.0d0))
    
    !Diagram      0; Contraction 3; Tree Level  2; Scaling  1/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  1/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("E1(n1,f1)+=F3(n1,f1)*O01()", &
    E1,F3,one_tensor,prefactor=(2.0d0,0.0d0))
    
    !Diagram      0; Contraction 4; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  0/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z0()+=T1(f1,n1)*E1(n1,f1)", &
    Z0,T1,E1,prefactor=(5.0d-1,0.0d0))
    
    ierr=exatns_tensor_destroy(E1)
    
    !Diagram      0; Contraction 5; Tree Level  0; Scaling  3/ 3/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  1/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z1(e1,m1)+=F3(n1,f1)*T2(e1,f1,m1,n1)", &
    Z1,F3,T2,prefactor=(1.0d0,0.0d0))
    
    allocate(tens_id(4), tens_root(4))
    tens_id   = (/nocc_id,nvir_id,nvir_id,nocc_id/)
    tens_root   = (/nocc_root,nvir_root,nvir_root,nocc_root/)
    ierr=exatns_tensor_create(J1,"J1",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(J1,'ZERO')
    
    !Diagram      0; Contraction 6; Tree Level  3; Scaling  4/ 4/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("J1(l1,f1,d1,n1)+=V7(l1,m2,d1,e2)*T2(e2,f1,m2,n1)", &
    J1,V7,T2,prefactor=(1.0d0,0.0d0))
    
    allocate(tens_id(4), tens_root(4))
    tens_id   = (/nocc_id,nvir_id,nvir_id,nocc_id/)
    tens_root   = (/nocc_root,nvir_root,nvir_root,nocc_root/)
    ierr=exatns_tensor_create(M1,"M1",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(M1,'ZERO')
    
    !Diagram      0; Contraction 7; Tree Level  2; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("M1(n1,e1,f1,m1)+=J1(n1,e1,f1,m1)*O01()", &
    M1,J1,one_tensor,prefactor=(1.0d0,0.0d0))
    
    !Diagram      0; Contraction 8; Tree Level  2; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("M1(n1,e1,f1,m1)+=V5(e1,n1,m1,f1)*O01()", &
    M1,V5,one_tensor,prefactor=(1.0d0,0.0d0))
    
    allocate(tens_id(4), tens_root(4))
    tens_id   = (/nocc_id,nocc_id,nvir_id,nocc_id/)
    tens_root   = (/nocc_root,nocc_root,nvir_root,nocc_root/)
    ierr=exatns_tensor_create(X1,"X1",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(X1,'ZERO')
    
    !Diagram      0; Contraction 9; Tree Level  4; Scaling  3/ 3/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("X1(n1,l1,d1,m1)+=V7(n1,l1,f1,d1)*T1(f1,m1)", &
    X1,V7,T1,prefactor=(1.0d0,0.0d0))
    
    !Diagram      0; Contraction 10; Tree Level  1; Scaling  5/ 3/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  1/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z1(e1,m1)+=V4(n1,l1,m1,f1)*T2(e1,f1,n1,l1)", &
    Z1,V4,T2,prefactor=(-5.0d-1,0.0d0))
    
    allocate(tens_id(2), tens_root(2))
    tens_id   = (/nocc_id,nocc_id/)
    tens_root   = (/nocc_root,nocc_root/)
    ierr=exatns_tensor_create(A2,"A2",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(A2,'ZERO')
    
    !Diagram      0; Contraction 11; Tree Level  3; Scaling  4/ 4/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("A2(n1,m1)+=V7(n1,l1,f1,d1)*T2(f1,d1,l1,m1)", &
    A2,V7,T2,prefactor=(1.0d0,0.0d0))
    
    allocate(tens_id(2), tens_root(2))
    tens_id   = (/nvir_id,nvir_id/)
    tens_root   = (/nvir_root,nvir_root/)
    ierr=exatns_tensor_create(I3,"I3",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(I3,'ZERO')
    
    !Diagram      0; Contraction 12; Tree Level  2; Scaling  2/ 4/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  0/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("I3(e1,f1)+=V8(e1,n1,f1,d1)*T1(d1,n1)", &
    I3,V8,T1,prefactor=(2.0d0,0.0d0))
    
    allocate(tens_id(4), tens_root(4))
    tens_id   = (/nocc_id,nocc_id,nvir_id,nocc_id/)
    tens_root   = (/nocc_root,nocc_root,nvir_root,nocc_root/)
    ierr=exatns_tensor_create(E2,"E2",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(E2,'ZERO')
    
    !Diagram      0; Contraction 13; Tree Level  3; Scaling  3/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("E2(n1,l1,d1,m1)+=X1(n1,l1,d1,m1)*O01()", &
    E2,X1,one_tensor,prefactor=(1.0d0,0.0d0))
    
    !Diagram      0; Contraction 14; Tree Level  3; Scaling  3/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("E2(n1,l1,d1,m1)+=V4(n1,l1,m1,d1)*O01()", &
    E2,V4,one_tensor,prefactor=(1.0d0,0.0d0))
    
    allocate(tens_id(2), tens_root(2))
    tens_id   = (/nocc_id,nocc_id/)
    tens_root   = (/nocc_root,nocc_root/)
    ierr=exatns_tensor_create(G2,"G2",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(G2,'ZERO')
    
    !Diagram      0; Contraction 15; Tree Level  3; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("G2(n1,m1)+=F3(n1,f1)*T1(f1,m1)", &
    G2,F3,T1,prefactor=(1.0d0,0.0d0))
    
    allocate(tens_id(2), tens_root(2))
    tens_id   = (/nocc_id,nocc_id/)
    tens_root   = (/nocc_root,nocc_root/)
    ierr=exatns_tensor_create(A3,"A3",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(A3,'ZERO')
    
    !Diagram      0; Contraction 16; Tree Level  2; Scaling  2/ 0/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("A3(n1,m1)+=G2(n1,m1)*O01()", &
    A3,G2,one_tensor,prefactor=(-2.0d0,0.0d0))
    
    !Diagram      0; Contraction 17; Tree Level  2; Scaling  2/ 0/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("A3(n1,m1)+=F1(n1,m1)*O01()", &
    A3,F1,one_tensor,prefactor=(-2.0d0,0.0d0))
    
    !Diagram      0; Contraction 18; Tree Level  1; Scaling  3/ 3/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  1/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z1(e1,m1)+=T1(f1,n1)*M1(n1,e1,f1,m1)", &
    Z1,T1,M1,prefactor=(1.0d0,0.0d0))
    
    ierr=exatns_tensor_destroy(M1)
    
    !Diagram      0; Contraction 19; Tree Level  1; Scaling  3/ 5/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  1/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z1(e1,m1)+=V8(e1,n1,f1,d1)*T2(f1,d1,m1,n1)", &
    Z1,V8,T2,prefactor=(5.0d-1,0.0d0))
    
    !Diagram      0; Contraction 20; Tree Level  2; Scaling  4/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("A3(n1,m1)+=T1(d1,l1)*E2(n1,l1,d1,m1)", &
    A3,T1,E2,prefactor=(-2.0d0,0.0d0))
    
    ierr=exatns_tensor_destroy(E2)
    
    !Diagram      0; Contraction 21; Tree Level  2; Scaling  2/ 0/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("A3(n1,m1)+=A2(n1,m1)*O01()", &
    A3,A2,one_tensor,prefactor=(1.0d0,0.0d0))
    
    !Diagram      0; Contraction 22; Tree Level  1; Scaling  3/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  1/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z1(e1,m1)+=T1(e1,n1)*A3(n1,m1)", &
    Z1,T1,A3,prefactor=(5.0d-1,0.0d0))
    
    ierr=exatns_tensor_destroy(A3)
    
    allocate(tens_id(2), tens_root(2))
    tens_id   = (/nvir_id,nvir_id/)
    tens_root   = (/nvir_root,nvir_root/)
    ierr=exatns_tensor_create(E3,"E3",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(E3,'ZERO')
    
    !Diagram      0; Contraction 23; Tree Level  3; Scaling  4/ 4/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  0/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("E3(f1,d1)+=V7(l1,m2,d1,e2)*T2(e2,f1,l1,m2)", &
    E3,V7,T2,prefactor=(1.0d0,0.0d0))
    
    !Diagram      0; Contraction 24; Tree Level  2; Scaling  0/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  0/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("I3(e1,f1)+=E3(e1,f1)*O01()", &
    I3,E3,one_tensor,prefactor=(1.0d0,0.0d0))
    
    !Diagram      0; Contraction 25; Tree Level  2; Scaling  0/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  0/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("I3(e1,f1)+=F4(e1,f1)*O01()", &
    I3,F4,one_tensor,prefactor=(2.0d0,0.0d0))
    
    !Diagram      0; Contraction 26; Tree Level  1; Scaling  1/ 3/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  1/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z1(e1,m1)+=T1(f1,m1)*I3(e1,f1)", &
    Z1,T1,I3,prefactor=(5.0d-1,0.0d0))
    
    ierr=exatns_tensor_destroy(I3)
    
    !Diagram      0; Contraction 27; Tree Level  1; Scaling  1/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  1/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z1(e1,m1)+=F2(e1,m1)*O01()", &
    Z1,F2,one_tensor,prefactor=(1.0d0,0.0d0))
    
    !ierr=exatns_tensor_destroy(F2)
    
    allocate(tens_id(4), tens_root(4))
    tens_id   = (/nocc_id,nocc_id,nocc_id,nocc_id/)
    tens_root   = (/nocc_root,nocc_root,nocc_root,nocc_root/)
    ierr=exatns_tensor_create(M3,"M3",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(M3,'ZERO')
    
    !Diagram      0; Contraction 28; Tree Level  4; Scaling  4/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  4/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("M3(l1,m2,n1,m1)+=T1(e2,n1)*X1(l1,m2,e2,m1)", &
    M3,T1,X1,prefactor=(1.0d0,0.0d0))
    
    allocate(tens_id(4), tens_root(4))
    tens_id   = (/nocc_id,nocc_id,nocc_id,nocc_id/)
    tens_root   = (/nocc_root,nocc_root,nocc_root,nocc_root/)
    ierr=exatns_tensor_create(X3,"X3",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(X3,'ZERO')
    
    !Diagram      0; Contraction 29; Tree Level  4; Scaling  4/ 4/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  4/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("X3(l1,m2,m1,n1)+=V7(l1,m2,d1,e2)*T2(d1,e2,m1,n1)", &
    X3,V7,T2,prefactor=(1.0d0,0.0d0))
    
    allocate(tens_id(2), tens_root(2))
    tens_id   = (/nocc_id,nvir_id/)
    tens_root   = (/nocc_root,nvir_root/)
    ierr=exatns_tensor_create(Y3,"Y3",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(Y3,'ZERO')
    
    !Diagram      0; Contraction 30; Tree Level  4; Scaling  3/ 3/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  1/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Y3(l1,e2)+=V7(l1,m2,d1,e2)*T1(d1,m2)", &
    Y3,V7,T1,prefactor=(1.0d0,0.0d0))
    
    !ierr=exatns_tensor_destroy(V7)
    
    allocate(tens_id(4), tens_root(4))
    tens_id   = (/nvir_id,nvir_id,nocc_id,nocc_id/)
    tens_root   = (/nvir_root,nvir_root,nocc_root,nocc_root/)
    ierr=exatns_tensor_create(A4,"A4",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(A4,'ZERO')
    
    !Diagram      0; Contraction 31; Tree Level  2; Scaling  4/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("A4(f1,e1,m1,n1)+=F1(l1,m1)*T2(f1,e1,n1,l1)", &
    A4,F1,T2,prefactor=(1.0d0,0.0d0))
    
    !ierr=exatns_tensor_destroy(F1)
    
    !Diagram      0; Contraction 32; Tree Level  0; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=A4(f1,e1,m1,n1)*O01()", &
    Z2,A4,one_tensor,prefactor=(-1.0d0,0.0d0))
    
    !Diagram      0; Contraction 33; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=A4(f1,e1,n1,m1)*O01()", &
    Z2,A4,one_tensor,prefactor=(1.0d0,0.0d0))
    
    ierr=exatns_tensor_destroy(A4)
    
    allocate(tens_id(4), tens_root(4))
    tens_id   = (/nvir_id,nvir_id,nocc_id,nocc_id/)
    tens_root   = (/nvir_root,nvir_root,nocc_root,nocc_root/)
    ierr=exatns_tensor_create(D4,"D4",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(D4,'ZERO')
    
    !Diagram      0; Contraction 34; Tree Level  2; Scaling  4/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("D4(e1,f1,n1,m1)+=T2(e1,f1,l1,n1)*G2(l1,m1)", &
    D4,T2,G2,prefactor=(1.0d0,0.0d0))
    
    ierr=exatns_tensor_destroy(G2)
    
    !Diagram      0; Contraction 35; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=D4(e1,f1,n1,m1)*O01()", &
    Z2,D4,one_tensor,prefactor=(-1.0d0,0.0d0))
    
    !Diagram      0; Contraction 36; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=D4(e1,f1,m1,n1)*O01()", &
    Z2,D4,one_tensor,prefactor=(1.0d0,0.0d0))
    
    ierr=exatns_tensor_destroy(D4)
    
    allocate(tens_id(4), tens_root(4))
    tens_id   = (/nvir_id,nocc_id,nvir_id,nocc_id/)
    tens_root   = (/nvir_root,nocc_root,nvir_root,nocc_root/)
    ierr=exatns_tensor_create(E4,"E4",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(E4,'ZERO')
    
    !Diagram      0; Contraction 37; Tree Level  4; Scaling  2/ 4/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("E4(e1,l1,d1,n1)+=V8(e1,l1,d1,e2)*T1(e2,n1)", &
    E4,V8,T1,prefactor=(1.0d0,0.0d0))
    
    allocate(tens_id(4), tens_root(4))
    tens_id   = (/nvir_id,nocc_id,nocc_id,nocc_id/)
    tens_root   = (/nvir_root,nocc_root,nocc_root,nocc_root/)
    ierr=exatns_tensor_create(G4,"G4",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(G4,'ZERO')
    
    !Diagram      0; Contraction 38; Tree Level  3; Scaling  3/ 5/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("G4(e1,l1,m1,n1)+=V8(e1,l1,d1,e2)*T2(d1,e2,m1,n1)", &
    G4,V8,T2,prefactor=(1.0d0,0.0d0))
    
    allocate(tens_id(4), tens_root(4))
    tens_id   = (/nvir_id,nvir_id,nocc_id,nocc_id/)
    tens_root   = (/nvir_root,nvir_root,nocc_root,nocc_root/)
    ierr=exatns_tensor_create(I4,"I4",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(I4,'ZERO')
    
    !Diagram      0; Contraction 39; Tree Level  2; Scaling  2/ 4/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("I4(e1,f1,m1,n1)+=V6(e1,f1,m1,d1)*T1(d1,n1)", &
    I4,V6,T1,prefactor=(1.0d0,0.0d0))
    
    !ierr=exatns_tensor_destroy(V6)
    
    !Diagram      0; Contraction 40; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=I4(e1,f1,m1,n1)*O01()", &
    Z2,I4,one_tensor,prefactor=(1.0d0,0.0d0))
    
    !Diagram      0; Contraction 41; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=I4(e1,f1,n1,m1)*O01()", &
    Z2,I4,one_tensor,prefactor=(-1.0d0,0.0d0))
    
    ierr=exatns_tensor_destroy(I4)
    
    allocate(tens_id(4), tens_root(4))
    tens_id   = (/nvir_id,nocc_id,nocc_id,nocc_id/)
    tens_root   = (/nvir_root,nocc_root,nocc_root,nocc_root/)
    ierr=exatns_tensor_create(J4,"J4",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(J4,'ZERO')
    
    !Diagram      0; Contraction 42; Tree Level  3; Scaling  3/ 3/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("J4(e1,l1,m1,n1)+=V5(e1,l1,m1,d1)*T1(d1,n1)", &
    J4,V5,T1,prefactor=(1.0d0,0.0d0))
    
    allocate(tens_id(4), tens_root(4))
    tens_id   = (/nvir_id,nocc_id,nvir_id,nocc_id/)
    tens_root   = (/nvir_root,nocc_root,nvir_root,nocc_root/)
    ierr=exatns_tensor_create(M4,"M4",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(M4,'ZERO')
    
    !Diagram      0; Contraction 43; Tree Level  3; Scaling  2/ 4/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("M4(e1,l1,e2,m1)+=V8(e1,l1,d1,e2)*T1(d1,m1)", &
    M4,V8,T1,prefactor=(1.0d0,0.0d0))
    
    allocate(tens_id(4), tens_root(4))
    tens_id   = (/nvir_id,nocc_id,nocc_id,nocc_id/)
    tens_root   = (/nvir_root,nocc_root,nocc_root,nocc_root/)
    ierr=exatns_tensor_create(X4,"X4",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(X4,'ZERO')
    
    !Diagram      0; Contraction 44; Tree Level  3; Scaling  3/ 3/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("X4(f1,l1,m1,n1)+=T2(e2,f1,m1,n1)*Y3(l1,e2)", &
    X4,T2,Y3,prefactor=(1.0d0,0.0d0))
    
    ierr=exatns_tensor_destroy(Y3)
    
    allocate(tens_id(4), tens_root(4))
    tens_id   = (/nvir_id,nvir_id,nocc_id,nocc_id/)
    tens_root   = (/nvir_root,nvir_root,nocc_root,nocc_root/)
    ierr=exatns_tensor_create(Y4,"Y4",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(Y4,'ZERO')
    
    !Diagram      0; Contraction 45; Tree Level  2; Scaling  2/ 4/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Y4(e1,f1,m1,n1)+=T2(e1,d1,m1,n1)*E3(f1,d1)", &
    Y4,T2,E3,prefactor=(1.0d0,0.0d0))
    
    ierr=exatns_tensor_destroy(E3)
    
    !Diagram      0; Contraction 46; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=Y4(e1,f1,m1,n1)*O01()", &
    Z2,Y4,one_tensor,prefactor=(5.0d-1,0.0d0))
    
    !Diagram      0; Contraction 47; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=Y4(f1,e1,m1,n1)*O01()", &
    Z2,Y4,one_tensor,prefactor=(-5.0d-1,0.0d0))
    
    ierr=exatns_tensor_destroy(Y4)
    
    allocate(tens_id(4), tens_root(4))
    tens_id   = (/nocc_id,nocc_id,nocc_id,nocc_id/)
    tens_root   = (/nocc_root,nocc_root,nocc_root,nocc_root/)
    ierr=exatns_tensor_create(M6,"M6",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(M6,'ZERO')
    
    !Diagram      0; Contraction 48; Tree Level  3; Scaling  4/ 0/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  4/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("M6(m2,l1,n1,m1)+=V1(l1,m2,m1,n1)*O01()", &
    M6,V1,one_tensor,prefactor=(1.0d0,0.0d0))
    
    !Diagram      0; Contraction 49; Tree Level  3; Scaling  4/ 0/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  4/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("M6(m2,l1,n1,m1)+=V1(m2,l1,m1,n1)*O01()", &
    M6,V1,one_tensor,prefactor=(-1.0d0,0.0d0))
    
    allocate(tens_id(2), tens_root(2))
    tens_id   = (/nvir_id,nvir_id/)
    tens_root   = (/nvir_root,nvir_root/)
    ierr=exatns_tensor_create(D5,"D5",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(D5,'ZERO')
    
    !Diagram      0; Contraction 50; Tree Level  3; Scaling  2/ 4/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  0/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("D5(e1,e2)+=V8(e1,l1,d1,e2)*T1(d1,l1)", &
    D5,V8,T1,prefactor=(1.0d0,0.0d0))
    
    !ierr=exatns_tensor_destroy(V8)
    
    allocate(tens_id(4), tens_root(4))
    tens_id   = (/nvir_id,nvir_id,nocc_id,nocc_id/)
    tens_root   = (/nvir_root,nvir_root,nocc_root,nocc_root/)
    ierr=exatns_tensor_create(E5,"E5",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(E5,'ZERO')
    
    !Diagram      0; Contraction 51; Tree Level  2; Scaling  2/ 4/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("E5(e1,f1,n1,m1)+=F4(e1,d1)*T2(f1,d1,n1,m1)", &
    E5,F4,T2,prefactor=(1.0d0,0.0d0))
    
    !ierr=exatns_tensor_destroy(F4)
    
    !Diagram      0; Contraction 52; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=E5(e1,f1,n1,m1)*O01()", &
    Z2,E5,one_tensor,prefactor=(1.0d0,0.0d0))
    
    !Diagram      0; Contraction 53; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=E5(f1,e1,n1,m1)*O01()", &
    Z2,E5,one_tensor,prefactor=(-1.0d0,0.0d0))
    
    ierr=exatns_tensor_destroy(E5)
    
    allocate(tens_id(4), tens_root(4))
    tens_id   = (/nvir_id,nvir_id,nocc_id,nocc_id/)
    tens_root   = (/nvir_root,nvir_root,nocc_root,nocc_root/)
    ierr=exatns_tensor_create(G5,"G5",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(G5,'ZERO')
    
    !Diagram      0; Contraction 54; Tree Level  2; Scaling  4/ 4/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("G5(f1,e1,n1,m1)+=T2(e2,f1,l1,n1)*M4(e1,l1,e2,m1)", &
    G5,T2,M4,prefactor=(1.0d0,0.0d0))
    
    ierr=exatns_tensor_destroy(M4)
    
    !Diagram      0; Contraction 55; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=G5(f1,e1,n1,m1)*O01()", &
    Z2,G5,one_tensor,prefactor=(1.0d0,0.0d0))
    
    !Diagram      0; Contraction 56; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=G5(e1,f1,n1,m1)*O01()", &
    Z2,G5,one_tensor,prefactor=(-1.0d0,0.0d0))
    
    !Diagram      0; Contraction 57; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=G5(f1,e1,m1,n1)*O01()", &
    Z2,G5,one_tensor,prefactor=(-1.0d0,0.0d0))
    
    !Diagram      0; Contraction 58; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=G5(e1,f1,m1,n1)*O01()", &
    Z2,G5,one_tensor,prefactor=(1.0d0,0.0d0))
    
    ierr=exatns_tensor_destroy(G5)
    
    allocate(tens_id(4), tens_root(4))
    tens_id   = (/nvir_id,nocc_id,nocc_id,nocc_id/)
    tens_root   = (/nvir_root,nocc_root,nocc_root,nocc_root/)
    ierr=exatns_tensor_create(I5,"I5",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(I5,'ZERO')
    
    !Diagram      0; Contraction 59; Tree Level  3; Scaling  5/ 3/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("I5(f1,l1,n1,m1)+=T2(e2,f1,m2,n1)*X1(l1,m2,e2,m1)", &
    I5,T2,X1,prefactor=(1.0d0,0.0d0))
    
    allocate(tens_id(4), tens_root(4))
    tens_id   = (/nocc_id,nvir_id,nocc_id,nocc_id/)
    tens_root   = (/nocc_root,nvir_root,nocc_root,nocc_root/)
    ierr=exatns_tensor_create(J5,"J5",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(J5,'ZERO')
    
    !Diagram      0; Contraction 60; Tree Level  3; Scaling  3/ 3/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("J5(l1,f1,m1,n1)+=F3(l1,d1)*T2(d1,f1,m1,n1)", &
    J5,F3,T2,prefactor=(1.0d0,0.0d0))
    
    !ierr=exatns_tensor_destroy(F3)
    
    allocate(tens_id(4), tens_root(4))
    tens_id   = (/nvir_id,nvir_id,nvir_id,nocc_id/)
    tens_root   = (/nvir_root,nvir_root,nvir_root,nocc_root/)
    ierr=exatns_tensor_create(M5,"M5",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(M5,'ZERO')
    
    !Diagram      0; Contraction 61; Tree Level  3; Scaling  1/ 5/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  1/ 3/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("M5(e1,f1,d1,n1)+=V9(e1,f1,d1,e2)*T1(e2,n1)", &
    M5,V9,T1,prefactor=(1.0d0,0.0d0))
    
    allocate(tens_id(4), tens_root(4))
    tens_id   = (/nvir_id,nvir_id,nocc_id,nocc_id/)
    tens_root   = (/nvir_root,nvir_root,nocc_root,nocc_root/)
    ierr=exatns_tensor_create(X5,"X5",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(X5,'ZERO')
    
    !Diagram      0; Contraction 62; Tree Level  2; Scaling  2/ 4/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("X5(e1,f1,m1,n1)+=T1(d1,m1)*M5(e1,f1,d1,n1)", &
    X5,T1,M5,prefactor=(1.0d0,0.0d0))
    
    ierr=exatns_tensor_destroy(M5)
    
    !Diagram      0; Contraction 63; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=X5(e1,f1,m1,n1)*O01()", &
    Z2,X5,one_tensor,prefactor=(5.0d-1,0.0d0))
    
    !Diagram      0; Contraction 64; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=X5(e1,f1,n1,m1)*O01()", &
    Z2,X5,one_tensor,prefactor=(-5.0d-1,0.0d0))
    
    ierr=exatns_tensor_destroy(X5)
    
    allocate(tens_id(4), tens_root(4))
    tens_id   = (/nvir_id,nvir_id,nocc_id,nocc_id/)
    tens_root   = (/nvir_root,nvir_root,nocc_root,nocc_root/)
    ierr=exatns_tensor_create(Y5,"Y5",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(Y5,'ZERO')
    
    !Diagram      0; Contraction 65; Tree Level  2; Scaling  4/ 4/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Y5(e1,f1,m1,n1)+=V5(e1,l1,m1,d1)*T2(f1,d1,n1,l1)", &
    Y5,V5,T2,prefactor=(1.0d0,0.0d0))
    
    !ierr=exatns_tensor_destroy(V5)
    
    !Diagram      0; Contraction 66; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=Y5(e1,f1,m1,n1)*O01()", &
    Z2,Y5,one_tensor,prefactor=(1.0d0,0.0d0))
    
    !Diagram      0; Contraction 67; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=Y5(f1,e1,m1,n1)*O01()", &
    Z2,Y5,one_tensor,prefactor=(-1.0d0,0.0d0))
    
    !Diagram      0; Contraction 68; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=Y5(e1,f1,n1,m1)*O01()", &
    Z2,Y5,one_tensor,prefactor=(-1.0d0,0.0d0))
    
    !Diagram      0; Contraction 69; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=Y5(f1,e1,n1,m1)*O01()", &
    Z2,Y5,one_tensor,prefactor=(1.0d0,0.0d0))
    
    ierr=exatns_tensor_destroy(Y5)
    
    allocate(tens_id(4), tens_root(4))
    tens_id   = (/nocc_id,nocc_id,nocc_id,nocc_id/)
    tens_root   = (/nocc_root,nocc_root,nocc_root,nocc_root/)
    ierr=exatns_tensor_create(A6,"A6",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(A6,'ZERO')
    
    !Diagram      0; Contraction 70; Tree Level  4; Scaling  4/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  4/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("A6(l1,m2,m1,n1)+=V4(l1,m2,m1,d1)*T1(d1,n1)", &
    A6,V4,T1,prefactor=(1.0d0,0.0d0))
    
    allocate(tens_id(4), tens_root(4))
    tens_id   = (/nocc_id,nocc_id,nocc_id,nocc_id/)
    tens_root   = (/nocc_root,nocc_root,nocc_root,nocc_root/)
    ierr=exatns_tensor_create(X10,"X10",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(X10,'ZERO')
    
    !Diagram      0; Contraction 71; Tree Level  2; Scaling  4/ 0/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  4/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("X10(l1,m2,m1,n1)+=A6(l1,m2,m1,n1)*O01()", &
    X10,A6,one_tensor,prefactor=(2.0d0,0.0d0))
    
    !Diagram      0; Contraction 72; Tree Level  2; Scaling  4/ 0/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  4/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("X10(l1,m2,m1,n1)+=A6(l1,m2,n1,m1)*O01()", &
    X10,A6,one_tensor,prefactor=(-2.0d0,0.0d0))
    
    allocate(tens_id(4), tens_root(4))
    tens_id   = (/nocc_id,nocc_id,nocc_id,nocc_id/)
    tens_root   = (/nocc_root,nocc_root,nocc_root,nocc_root/)
    ierr=exatns_tensor_create(A11,"A11",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(A11,'ZERO')
    
    !Diagram      0; Contraction 73; Tree Level  3; Scaling  4/ 0/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  4/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("A11(m2,l1,n1,m1)+=M3(l1,m2,n1,m1)*O01()", &
    A11,M3,one_tensor,prefactor=(-1.0d0,0.0d0))
    
    !Diagram      0; Contraction 74; Tree Level  3; Scaling  4/ 0/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  4/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("A11(m2,l1,n1,m1)+=A6(l1,m2,m1,n1)*O01()", &
    A11,A6,one_tensor,prefactor=(-2.0d0,0.0d0))
    
    !Diagram      0; Contraction 75; Tree Level  3; Scaling  4/ 0/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  4/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("A11(m2,l1,n1,m1)+=M3(l1,m2,m1,n1)*O01()", &
    A11,M3,one_tensor,prefactor=(1.0d0,0.0d0))
    
    !Diagram      0; Contraction 76; Tree Level  3; Scaling  4/ 0/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  4/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("M6(m2,l1,n1,m1)+=A6(m2,l1,m1,n1)*O01()", &
    M6,A6,one_tensor,prefactor=(-1.0d0,0.0d0))
    
    !Diagram      0; Contraction 77; Tree Level  3; Scaling  4/ 0/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  4/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("M6(m2,l1,n1,m1)+=A6(l1,m2,n1,m1)*O01()", &
    M6,A6,one_tensor,prefactor=(-1.0d0,0.0d0))
    
    !Diagram      0; Contraction 78; Tree Level  3; Scaling  4/ 0/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  4/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("M6(m2,l1,n1,m1)+=A6(m2,l1,n1,m1)*O01()", &
    M6,A6,one_tensor,prefactor=(1.0d0,0.0d0))
    
    ierr=exatns_tensor_destroy(A6)
    
    allocate(tens_id(4), tens_root(4))
    tens_id   = (/nocc_id,nvir_id,nocc_id,nocc_id/)
    tens_root   = (/nocc_root,nvir_root,nocc_root,nocc_root/)
    ierr=exatns_tensor_create(X6,"X6",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(X6,'ZERO')
    
    !Diagram      0; Contraction 79; Tree Level  3; Scaling  5/ 3/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("X6(l1,f1,m1,n1)+=V4(l1,m2,m1,d1)*T2(d1,f1,m2,n1)", &
    X6,V4,T2,prefactor=(1.0d0,0.0d0))
    
    allocate(tens_id(4), tens_root(4))
    tens_id   = (/nvir_id,nocc_id,nocc_id,nocc_id/)
    tens_root   = (/nvir_root,nocc_root,nocc_root,nocc_root/)
    ierr=exatns_tensor_create(E10,"E10",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(E10,'ZERO')
    
    !Diagram      0; Contraction 80; Tree Level  2; Scaling  3/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("E10(e1,l1,m1,n1)+=X6(l1,e1,m1,n1)*O01()", &
    E10,X6,one_tensor,prefactor=(-4.0d0,0.0d0))
    
    !Diagram      0; Contraction 81; Tree Level  2; Scaling  3/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("E10(e1,l1,m1,n1)+=X6(l1,e1,n1,m1)*O01()", &
    E10,X6,one_tensor,prefactor=(4.0d0,0.0d0))
    
    allocate(tens_id(4), tens_root(4))
    tens_id   = (/nvir_id,nvir_id,nocc_id,nocc_id/)
    tens_root   = (/nvir_root,nvir_root,nocc_root,nocc_root/)
    ierr=exatns_tensor_create(A7,"A7",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(A7,'ZERO')
    
    !Diagram      0; Contraction 82; Tree Level  2; Scaling  4/ 4/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("A7(e1,f1,m1,n1)+=T2(e1,d1,m1,l1)*J1(l1,f1,d1,n1)", &
    A7,T2,J1,prefactor=(1.0d0,0.0d0))
    
    ierr=exatns_tensor_destroy(J1)
    
    !Diagram      0; Contraction 83; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=A7(e1,f1,m1,n1)*O01()", &
    Z2,A7,one_tensor,prefactor=(5.0d-1,0.0d0))
    
    !Diagram      0; Contraction 84; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=A7(f1,e1,m1,n1)*O01()", &
    Z2,A7,one_tensor,prefactor=(-5.0d-1,0.0d0))
    
    !Diagram      0; Contraction 85; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=A7(e1,f1,n1,m1)*O01()", &
    Z2,A7,one_tensor,prefactor=(-5.0d-1,0.0d0))
    
    !Diagram      0; Contraction 86; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=A7(f1,e1,n1,m1)*O01()", &
    Z2,A7,one_tensor,prefactor=(5.0d-1,0.0d0))
    
    ierr=exatns_tensor_destroy(A7)
    
    allocate(tens_id(4), tens_root(4))
    tens_id   = (/nvir_id,nocc_id,nocc_id,nocc_id/)
    tens_root   = (/nvir_root,nocc_root,nocc_root,nocc_root/)
    ierr=exatns_tensor_create(M11,"M11",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(M11,'ZERO')
    
    !Diagram      0; Contraction 87; Tree Level  2; Scaling  3/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("M11(f1,l1,m1,n1)+=J4(f1,l1,m1,n1)*O01()", &
    M11,J4,one_tensor,prefactor=(4.0d0,0.0d0))
    
    !Diagram      0; Contraction 88; Tree Level  2; Scaling  3/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("M11(f1,l1,m1,n1)+=J4(f1,l1,n1,m1)*O01()", &
    M11,J4,one_tensor,prefactor=(-4.0d0,0.0d0))
    
    !Diagram      0; Contraction 89; Tree Level  2; Scaling  3/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("E10(e1,l1,m1,n1)+=J5(l1,e1,m1,n1)*O01()", &
    E10,J5,one_tensor,prefactor=(-4.0d0,0.0d0))
    
    !Diagram      0; Contraction 90; Tree Level  2; Scaling  3/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("E10(e1,l1,m1,n1)+=X4(e1,l1,m1,n1)*O01()", &
    E10,X4,one_tensor,prefactor=(4.0d0,0.0d0))
    
    allocate(tens_id(4), tens_root(4))
    tens_id   = (/nvir_id,nvir_id,nocc_id,nocc_id/)
    tens_root   = (/nvir_root,nvir_root,nocc_root,nocc_root/)
    ierr=exatns_tensor_create(G7,"G7",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(G7,'ZERO')
    
    !Diagram      0; Contraction 91; Tree Level  2; Scaling  4/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("G7(e1,f1,m1,n1)+=T2(e1,f1,m1,l1)*A2(l1,n1)", &
    G7,T2,A2,prefactor=(1.0d0,0.0d0))
    
    ierr=exatns_tensor_destroy(A2)
    
    !Diagram      0; Contraction 92; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=G7(e1,f1,m1,n1)*O01()", &
    Z2,G7,one_tensor,prefactor=(5.0d-1,0.0d0))
    
    !Diagram      0; Contraction 93; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=G7(e1,f1,n1,m1)*O01()", &
    Z2,G7,one_tensor,prefactor=(-5.0d-1,0.0d0))
    
    ierr=exatns_tensor_destroy(G7)
    
    !Diagram      0; Contraction 94; Tree Level  2; Scaling  3/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("E10(e1,l1,m1,n1)+=I5(e1,l1,n1,m1)*O01()", &
    E10,I5,one_tensor,prefactor=(-4.0d0,0.0d0))
    
    !Diagram      0; Contraction 95; Tree Level  2; Scaling  3/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("E10(e1,l1,m1,n1)+=I5(e1,l1,m1,n1)*O01()", &
    E10,I5,one_tensor,prefactor=(4.0d0,0.0d0))
    
    allocate(tens_id(2), tens_root(2))
    tens_id   = (/nocc_id,nocc_id/)
    tens_root   = (/nocc_root,nocc_root/)
    ierr=exatns_tensor_create(J7,"J7",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(J7,'ZERO')
    
    !Diagram      0; Contraction 96; Tree Level  3; Scaling  4/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("J7(m2,m1)+=T1(e2,l1)*X1(l1,m2,e2,m1)", &
    J7,T1,X1,prefactor=(1.0d0,0.0d0))
    
    ierr=exatns_tensor_destroy(X1)
    
    allocate(tens_id(4), tens_root(4))
    tens_id   = (/nvir_id,nvir_id,nocc_id,nocc_id/)
    tens_root   = (/nvir_root,nvir_root,nocc_root,nocc_root/)
    ierr=exatns_tensor_create(M7,"M7",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(M7,'ZERO')
    
    !Diagram      0; Contraction 97; Tree Level  2; Scaling  4/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("M7(e1,f1,n1,m1)+=T2(e1,f1,m2,n1)*J7(m2,m1)", &
    M7,T2,J7,prefactor=(1.0d0,0.0d0))
    
    ierr=exatns_tensor_destroy(J7)
    
    !Diagram      0; Contraction 98; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=M7(e1,f1,n1,m1)*O01()", &
    Z2,M7,one_tensor,prefactor=(1.0d0,0.0d0))
    
    !Diagram      0; Contraction 99; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=M7(e1,f1,m1,n1)*O01()", &
    Z2,M7,one_tensor,prefactor=(-1.0d0,0.0d0))
    
    ierr=exatns_tensor_destroy(M7)
    
    allocate(tens_id(4), tens_root(4))
    tens_id   = (/nvir_id,nvir_id,nocc_id,nocc_id/)
    tens_root   = (/nvir_root,nvir_root,nocc_root,nocc_root/)
    ierr=exatns_tensor_create(X7,"X7",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(X7,'ZERO')
    
    !Diagram      0; Contraction 100; Tree Level  2; Scaling  2/ 4/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("X7(f1,e1,m1,n1)+=T2(e2,f1,m1,n1)*D5(e1,e2)", &
    X7,T2,D5,prefactor=(1.0d0,0.0d0))
    
    ierr=exatns_tensor_destroy(D5)
    
    !Diagram      0; Contraction 101; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=X7(f1,e1,m1,n1)*O01()", &
    Z2,X7,one_tensor,prefactor=(-1.0d0,0.0d0))
    
    !Diagram      0; Contraction 102; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=X7(e1,f1,m1,n1)*O01()", &
    Z2,X7,one_tensor,prefactor=(1.0d0,0.0d0))
    
    ierr=exatns_tensor_destroy(X7)
    
    allocate(tens_id(2), tens_root(2))
    tens_id   = (/nocc_id,nocc_id/)
    tens_root   = (/nocc_root,nocc_root/)
    ierr=exatns_tensor_create(Y7,"Y7",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(Y7,'ZERO')
    
    !Diagram      0; Contraction 103; Tree Level  3; Scaling  4/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Y7(m2,m1)+=V4(l1,m2,m1,d1)*T1(d1,l1)", &
    Y7,V4,T1,prefactor=(1.0d0,0.0d0))
    
    !ierr=exatns_tensor_destroy(V4)
    
    allocate(tens_id(4), tens_root(4))
    tens_id   = (/nvir_id,nvir_id,nocc_id,nocc_id/)
    tens_root   = (/nvir_root,nvir_root,nocc_root,nocc_root/)
    ierr=exatns_tensor_create(A8,"A8",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(A8,'ZERO')
    
    !Diagram      0; Contraction 104; Tree Level  2; Scaling  4/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("A8(e1,f1,n1,m1)+=T2(e1,f1,m2,n1)*Y7(m2,m1)", &
    A8,T2,Y7,prefactor=(1.0d0,0.0d0))
    
    ierr=exatns_tensor_destroy(Y7)
    
    !Diagram      0; Contraction 105; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=A8(e1,f1,n1,m1)*O01()", &
    Z2,A8,one_tensor,prefactor=(1.0d0,0.0d0))
    
    !Diagram      0; Contraction 106; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=A8(e1,f1,m1,n1)*O01()", &
    Z2,A8,one_tensor,prefactor=(-1.0d0,0.0d0))
    
    ierr=exatns_tensor_destroy(A8)
    
    allocate(tens_id(4), tens_root(4))
    tens_id   = (/nocc_id,nocc_id,nocc_id,nocc_id/)
    tens_root   = (/nocc_root,nocc_root,nocc_root,nocc_root/)
    ierr=exatns_tensor_create(D8,"D8",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(D8,'ZERO')
    
    !Diagram      0; Contraction 107; Tree Level  3; Scaling  4/ 0/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  4/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("D8(l1,m2,m1,n1)+=X3(l1,m2,m1,n1)*O01()", &
    D8,X3,one_tensor,prefactor=(1.0d0,0.0d0))
    
    !Diagram      0; Contraction 108; Tree Level  3; Scaling  4/ 0/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  4/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("D8(l1,m2,m1,n1)+=X3(m2,l1,m1,n1)*O01()", &
    D8,X3,one_tensor,prefactor=(-1.0d0,0.0d0))
    
    !Diagram      0; Contraction 109; Tree Level  2; Scaling  5/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("E10(e1,l1,m1,n1)+=T1(e1,m2)*D8(m2,l1,m1,n1)", &
    E10,T1,D8,prefactor=(-1.0d0,0.0d0))
    
    ierr=exatns_tensor_destroy(D8)
    
    !Diagram      0; Contraction 110; Tree Level  2; Scaling  3/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("E10(e1,l1,m1,n1)+=J4(e1,l1,m1,n1)*O01()", &
    E10,J4,one_tensor,prefactor=(4.0d0,0.0d0))
    
    !Diagram      0; Contraction 111; Tree Level  2; Scaling  3/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("E10(e1,l1,m1,n1)+=J4(e1,l1,n1,m1)*O01()", &
    E10,J4,one_tensor,prefactor=(-4.0d0,0.0d0))
    
    ierr=exatns_tensor_destroy(J4)
    
    allocate(tens_id(4), tens_root(4))
    tens_id   = (/nvir_id,nocc_id,nocc_id,nocc_id/)
    tens_root   = (/nvir_root,nocc_root,nocc_root,nocc_root/)
    ierr=exatns_tensor_create(J8,"J8",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(J8,'ZERO')
    
    !Diagram      0; Contraction 112; Tree Level  3; Scaling  3/ 3/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("J8(e1,l1,m1,n1)+=T1(d1,m1)*E4(e1,l1,d1,n1)", &
    J8,T1,E4,prefactor=(1.0d0,0.0d0))
    
    ierr=exatns_tensor_destroy(E4)
    
    !Diagram      0; Contraction 113; Tree Level  2; Scaling  3/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("E10(e1,l1,m1,n1)+=J8(e1,l1,m1,n1)*O01()", &
    E10,J8,one_tensor,prefactor=(2.0d0,0.0d0))
    
    !Diagram      0; Contraction 114; Tree Level  2; Scaling  3/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("E10(e1,l1,m1,n1)+=J8(e1,l1,n1,m1)*O01()", &
    E10,J8,one_tensor,prefactor=(-2.0d0,0.0d0))
    
    !Diagram      0; Contraction 115; Tree Level  2; Scaling  3/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("E10(e1,l1,m1,n1)+=G4(e1,l1,m1,n1)*O01()", &
    E10,G4,one_tensor,prefactor=(2.0d0,0.0d0))
    
    !Diagram      0; Contraction 116; Tree Level  2; Scaling  3/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("M11(f1,l1,m1,n1)+=J8(f1,l1,m1,n1)*O01()", &
    M11,J8,one_tensor,prefactor=(2.0d0,0.0d0))
    
    !Diagram      0; Contraction 117; Tree Level  2; Scaling  3/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("M11(f1,l1,m1,n1)+=J8(f1,l1,n1,m1)*O01()", &
    M11,J8,one_tensor,prefactor=(-2.0d0,0.0d0))
    
    ierr=exatns_tensor_destroy(J8)
    
    !Diagram      0; Contraction 118; Tree Level  2; Scaling  3/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("M11(f1,l1,m1,n1)+=I5(f1,l1,n1,m1)*O01()", &
    M11,I5,one_tensor,prefactor=(-4.0d0,0.0d0))
    
    !Diagram      0; Contraction 119; Tree Level  2; Scaling  3/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("M11(f1,l1,m1,n1)+=I5(f1,l1,m1,n1)*O01()", &
    M11,I5,one_tensor,prefactor=(4.0d0,0.0d0))
    
    ierr=exatns_tensor_destroy(I5)
    
    !Diagram      0; Contraction 120; Tree Level  2; Scaling  3/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("M11(f1,l1,m1,n1)+=X6(l1,f1,m1,n1)*O01()", &
    M11,X6,one_tensor,prefactor=(-4.0d0,0.0d0))
    
    !Diagram      0; Contraction 121; Tree Level  2; Scaling  3/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("M11(f1,l1,m1,n1)+=X6(l1,f1,n1,m1)*O01()", &
    M11,X6,one_tensor,prefactor=(4.0d0,0.0d0))
    
    ierr=exatns_tensor_destroy(X6)
    
    !Diagram      0; Contraction 122; Tree Level  2; Scaling  3/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("M11(f1,l1,m1,n1)+=G4(f1,l1,m1,n1)*O01()", &
    M11,G4,one_tensor,prefactor=(2.0d0,0.0d0))
    
    ierr=exatns_tensor_destroy(G4)
    
    !Diagram      0; Contraction 123; Tree Level  2; Scaling  5/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("E10(e1,l1,m1,n1)+=T1(e1,m2)*M6(l1,m2,n1,m1)", &
    E10,T1,M6,prefactor=(-2.0d0,0.0d0))
    
    ierr=exatns_tensor_destroy(M6)
    
    !Diagram      0; Contraction 124; Tree Level  2; Scaling  3/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("E10(e1,l1,m1,n1)+=V2(e1,l1,m1,n1)*O01()", &
    E10,V2,one_tensor,prefactor=(4.0d0,0.0d0))
    
    !Diagram      0; Contraction 125; Tree Level  1; Scaling  4/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=T1(f1,l1)*E10(e1,l1,m1,n1)", &
    Z2,T1,E10,prefactor=(-2.5d-1,0.0d0))
    
    ierr=exatns_tensor_destroy(E10)
    
    allocate(tens_id(4), tens_root(4))
    tens_id   = (/nocc_id,nocc_id,nocc_id,nocc_id/)
    tens_root   = (/nocc_root,nocc_root,nocc_root,nocc_root/)
    ierr=exatns_tensor_create(I10,"I10",tens_id, tens_root,EXA_DATA_KIND_C8)
    deallocate(tens_id,tens_root)
    ierr=exatns_tensor_init(I10,'ZERO')
    
    !Diagram      0; Contraction 126; Tree Level  3; Scaling  4/ 0/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  4/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("I10(l1,m2,n1,m1)+=M3(l1,m2,n1,m1)*O01()", &
    I10,M3,one_tensor,prefactor=(1.0d0,0.0d0))
    
    !Diagram      0; Contraction 127; Tree Level  3; Scaling  4/ 0/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  4/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("I10(l1,m2,n1,m1)+=M3(l1,m2,m1,n1)*O01()", &
    I10,M3,one_tensor,prefactor=(-1.0d0,0.0d0))
    
    ierr=exatns_tensor_destroy(M3)
    
    !Diagram      0; Contraction 128; Tree Level  2; Scaling  4/ 0/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  4/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("X10(l1,m2,m1,n1)+=I10(l1,m2,n1,m1)*O01()", &
    X10,I10,one_tensor,prefactor=(1.0d0,0.0d0))
    
    !Diagram      0; Contraction 129; Tree Level  2; Scaling  4/ 0/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  4/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("X10(l1,m2,m1,n1)+=X3(l1,m2,m1,n1)*O01()", &
    X10,X3,one_tensor,prefactor=(1.0d0,0.0d0))
    
    ierr=exatns_tensor_destroy(X3)
    
    !Diagram      0; Contraction 130; Tree Level  2; Scaling  4/ 0/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  4/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("X10(l1,m2,m1,n1)+=V1(l1,m2,m1,n1)*O01()", &
    X10,V1,one_tensor,prefactor=(2.0d0,0.0d0))
    
    !ierr=exatns_tensor_destroy(V1)
    
    !Diagram      0; Contraction 131; Tree Level  1; Scaling  6/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=T2(e1,f1,l1,m2)*X10(l1,m2,m1,n1)", &
    Z2,T2,X10,prefactor=(2.5d-1,0.0d0))
    
    ierr=exatns_tensor_destroy(X10)
    
    !Diagram      0; Contraction 132; Tree Level  3; Scaling  4/ 0/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  4/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("A11(m2,l1,n1,m1)+=I10(m2,l1,n1,m1)*O01()", &
    A11,I10,one_tensor,prefactor=(1.0d0,0.0d0))
    
    ierr=exatns_tensor_destroy(I10)
    
    !Diagram      0; Contraction 133; Tree Level  2; Scaling  5/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("M11(f1,l1,m1,n1)+=T1(f1,m2)*A11(m2,l1,n1,m1)", &
    M11,T1,A11,prefactor=(-1.0d0,0.0d0))
    
    ierr=exatns_tensor_destroy(A11)
    
    !Diagram      0; Contraction 134; Tree Level  2; Scaling  3/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("M11(f1,l1,m1,n1)+=X4(f1,l1,m1,n1)*O01()", &
    M11,X4,one_tensor,prefactor=(4.0d0,0.0d0))
    
    ierr=exatns_tensor_destroy(X4)
    
    !Diagram      0; Contraction 135; Tree Level  2; Scaling  3/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("M11(f1,l1,m1,n1)+=J5(l1,f1,m1,n1)*O01()", &
    M11,J5,one_tensor,prefactor=(-4.0d0,0.0d0))
    
    ierr=exatns_tensor_destroy(J5)
    
    !Diagram      0; Contraction 136; Tree Level  2; Scaling  3/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("M11(f1,l1,m1,n1)+=V2(f1,l1,m1,n1)*O01()", &
    M11,V2,one_tensor,prefactor=(4.0d0,0.0d0))
    
    !ierr=exatns_tensor_destroy(V2)
    
    !Diagram      0; Contraction 137; Tree Level  1; Scaling  4/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=T1(e1,l1)*M11(f1,l1,m1,n1)", &
    Z2,T1,M11,prefactor=(2.5d-1,0.0d0))
    
    ierr=exatns_tensor_destroy(M11)
    
    !ierr=exatns_tensor_destroy(T1)
    
    !Diagram      0; Contraction 138; Tree Level  1; Scaling  2/ 6/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=V9(e1,f1,d1,e2)*T2(d1,e2,m1,n1)", &
    Z2,V9,T2,prefactor=(5.0d-1,0.0d0))
    
    !ierr=exatns_tensor_destroy(T2)
    
    !ierr=exatns_tensor_destroy(V9)
    
    !Diagram      0; Contraction 139; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=exatns_tensor_contract("Z2(e1,f1,m1,n1)+=V3(e1,f1,m1,n1)*O01()", &
    Z2,V3,one_tensor,prefactor=(1.0d0,0.0d0))
    
    !ierr=exatns_tensor_destroy(V3)
    
    
    ierr=exatns_tensor_destroy(one_tensor)
    
end subroutine exatensor_tenpi_ccsd
#endif
