!
! CCSD_T6 generated by Jan Brandejs.
!

subroutine talsh_tenpi_ccsd(nocc,nvir,F1,F3,F2,F4,T1, &
        T2,V1,V4,V7,V2,V5,V8,V3,V6,V9, &
        Z0,Z1,Z2)
    
    use talsh
    use tensor_algebra
    use, intrinsic:: ISO_C_BINDING
    
    implicit none
    
    complex(8), parameter :: ZERO=(0.D0,0.D0),ONE_HALF=(0.5D0,0.D0), &
                             MINUS_ONE=(-1.D0,0.D0),ONE=(1.0D0,0.D0), MINUS_ONE_HALF=(-0.5D0,0.D0), &
                             MINUS_ONE_QUARTER=(-0.25D0,0.D0), ONE_QUARTER=(0.25D0,0.D0), &
                             MINUS_ONE_EIGHT=(-0.125D0,0.D0)
    
    
    integer, intent(in) :: nocc
    integer, intent(in) :: nvir
    type(talsh_tens_t), intent(inout) :: F1    !       OO
    type(talsh_tens_t), intent(inout) :: F3    !       OV
    type(talsh_tens_t), intent(inout) :: F2    !       VO
    type(talsh_tens_t), intent(inout) :: F4    !       VV
    type(talsh_tens_t), intent(inout) :: T1    !       VO
    type(talsh_tens_t), intent(inout) :: T2    !       VVOO
    type(talsh_tens_t), intent(inout) :: V1    !       OOOO
    type(talsh_tens_t), intent(inout) :: V4    !       OOOV
    type(talsh_tens_t), intent(inout) :: V7    !       OOVV
    type(talsh_tens_t), intent(inout) :: V2    !       VOOO
    type(talsh_tens_t), intent(inout) :: V5    !       VOOV
    type(talsh_tens_t), intent(inout) :: V8    !       VOVV
    type(talsh_tens_t), intent(inout) :: V3    !       VVOO
    type(talsh_tens_t), intent(inout) :: V6    !       VVOV
    type(talsh_tens_t), intent(inout) :: V9    !       VVVV
    type(talsh_tens_t), intent(inout) :: Z0    !       UnitTensor
    type(talsh_tens_t), intent(inout) :: Z1    !       VO
    type(talsh_tens_t), intent(inout) :: Z2    !       VVOO
    type(talsh_tens_t) :: E1    !       OV
    type(talsh_tens_t) :: J1    !       OVVO
    type(talsh_tens_t) :: M1    !       OVVO
    type(talsh_tens_t) :: X1    !       OOVO
    type(talsh_tens_t) :: A2    !       OO
    type(talsh_tens_t) :: I3    !       VV
    type(talsh_tens_t) :: E2    !       OOVO
    type(talsh_tens_t) :: G2    !       OO
    type(talsh_tens_t) :: A3    !       OO
    type(talsh_tens_t) :: E3    !       VV
    type(talsh_tens_t) :: M3    !       OOOO
    type(talsh_tens_t) :: X3    !       OOOO
    type(talsh_tens_t) :: Y3    !       OV
    type(talsh_tens_t) :: A4    !       VVOO
    type(talsh_tens_t) :: D4    !       VVOO
    type(talsh_tens_t) :: E4    !       VOVO
    type(talsh_tens_t) :: G4    !       VOOO
    type(talsh_tens_t) :: I4    !       VVOO
    type(talsh_tens_t) :: J4    !       VOOO
    type(talsh_tens_t) :: M4    !       VOVO
    type(talsh_tens_t) :: X4    !       VOOO
    type(talsh_tens_t) :: Y4    !       VVOO
    type(talsh_tens_t) :: M6    !       OOOO
    type(talsh_tens_t) :: D5    !       VV
    type(talsh_tens_t) :: E5    !       VVOO
    type(talsh_tens_t) :: G5    !       VVOO
    type(talsh_tens_t) :: I5    !       VOOO
    type(talsh_tens_t) :: J5    !       OVOO
    type(talsh_tens_t) :: M5    !       VVVO
    type(talsh_tens_t) :: X5    !       VVOO
    type(talsh_tens_t) :: Y5    !       VVOO
    type(talsh_tens_t) :: A6    !       OOOO
    type(talsh_tens_t) :: X10    !       OOOO
    type(talsh_tens_t) :: A11    !       OOOO
    type(talsh_tens_t) :: X6    !       OVOO
    type(talsh_tens_t) :: E10    !       VOOO
    type(talsh_tens_t) :: A7    !       VVOO
    type(talsh_tens_t) :: M11    !       VOOO
    type(talsh_tens_t) :: G7    !       VVOO
    type(talsh_tens_t) :: J7    !       OO
    type(talsh_tens_t) :: M7    !       VVOO
    type(talsh_tens_t) :: X7    !       VVOO
    type(talsh_tens_t) :: Y7    !       OO
    type(talsh_tens_t) :: A8    !       VVOO
    type(talsh_tens_t) :: D8    !       OOOO
    type(talsh_tens_t) :: J8    !       VOOO
    type(talsh_tens_t) :: I10    !       OOOO
    
    integer :: ierr
    
    write(*,*) "    Running code generated by tenpi.   "
    
    !Diagram      0; Contraction 1; Tree Level  0; Scaling  4/ 4/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  0/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("Z0()+=V7(m1,n1,e1,f1)*T2(e1,f1,m1,n1)", &
    Z0,V7,T2,scale=(2.5d-1,0.0d0))
    
    ierr=talsh_tensor_construct(E1, C8, (/nocc,nvir/), init_val=ZERO)
    
    !Diagram      0; Contraction 2; Tree Level  2; Scaling  3/ 3/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  1/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("E1(n1,f1)+=V7(m1,n1,e1,f1)*T1(e1,m1)", &
    E1,V7,T1,scale=(1.0d0,0.0d0))
    
    !Diagram      0; Contraction 3; Tree Level  2; Scaling  1/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  1/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("E1(n1,f1)+=F3(n1,f1)", &
    E1,F3,scale=(2.0d0,0.0d0))
    
    !Diagram      0; Contraction 4; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  0/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("Z0()+=T1(f1,n1)*E1(n1,f1)", &
    Z0,T1,E1,scale=(5.0d-1,0.0d0))
    
    ierr=talsh_tensor_destruct(E1)
    
    !Diagram      0; Contraction 5; Tree Level  0; Scaling  3/ 3/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  1/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("Z1(e1,m1)+=F3(n1,f1)*T2(e1,f1,m1,n1)", &
    Z1,F3,T2,scale=(1.0d0,0.0d0))
    
    ierr=talsh_tensor_construct(J1, C8, (/nocc,nvir,nvir,nocc/), init_val=ZERO)
    
    !Diagram      0; Contraction 6; Tree Level  3; Scaling  4/ 4/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("J1(l1,f1,d1,n1)+=V7(l1,m2,d1,e2)*T2(e2,f1,m2,n1)", &
    J1,V7,T2,scale=(1.0d0,0.0d0))
    
    ierr=talsh_tensor_construct(M1, C8, (/nocc,nvir,nvir,nocc/), init_val=ZERO)
    
    !Diagram      0; Contraction 7; Tree Level  2; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("M1(n1,e1,f1,m1)+=J1(n1,e1,f1,m1)", &
    M1,J1,scale=(1.0d0,0.0d0))
    
    !Diagram      0; Contraction 8; Tree Level  2; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("M1(n1,e1,f1,m1)+=V5(e1,n1,m1,f1)", &
    M1,V5,scale=(1.0d0,0.0d0))
    
    ierr=talsh_tensor_construct(X1, C8, (/nocc,nocc,nvir,nocc/), init_val=ZERO)
    
    !Diagram      0; Contraction 9; Tree Level  4; Scaling  3/ 3/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("X1(n1,l1,d1,m1)+=V7(n1,l1,f1,d1)*T1(f1,m1)", &
    X1,V7,T1,scale=(1.0d0,0.0d0))
    
    !Diagram      0; Contraction 10; Tree Level  1; Scaling  5/ 3/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  1/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("Z1(e1,m1)+=V4(n1,l1,m1,f1)*T2(e1,f1,n1,l1)", &
    Z1,V4,T2,scale=(-5.0d-1,0.0d0))
    
    ierr=talsh_tensor_construct(A2, C8, (/nocc,nocc/), init_val=ZERO)
    
    !Diagram      0; Contraction 11; Tree Level  3; Scaling  4/ 4/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("A2(n1,m1)+=V7(n1,l1,f1,d1)*T2(f1,d1,l1,m1)", &
    A2,V7,T2,scale=(1.0d0,0.0d0))
    
    ierr=talsh_tensor_construct(I3, C8, (/nvir,nvir/), init_val=ZERO)
    
    !Diagram      0; Contraction 12; Tree Level  2; Scaling  2/ 4/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  0/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("I3(e1,f1)+=V8(e1,n1,f1,d1)*T1(d1,n1)", &
    I3,V8,T1,scale=(2.0d0,0.0d0))
    
    ierr=talsh_tensor_construct(E2, C8, (/nocc,nocc,nvir,nocc/), init_val=ZERO)
    
    !Diagram      0; Contraction 13; Tree Level  3; Scaling  3/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("E2(n1,l1,d1,m1)+=X1(n1,l1,d1,m1)", &
    E2,X1,scale=(1.0d0,0.0d0))
    
    !Diagram      0; Contraction 14; Tree Level  3; Scaling  3/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("E2(n1,l1,d1,m1)+=V4(n1,l1,m1,d1)", &
    E2,V4,scale=(1.0d0,0.0d0))
    
    ierr=talsh_tensor_construct(G2, C8, (/nocc,nocc/), init_val=ZERO)
    
    !Diagram      0; Contraction 15; Tree Level  3; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("G2(n1,m1)+=F3(n1,f1)*T1(f1,m1)", &
    G2,F3,T1,scale=(1.0d0,0.0d0))
    
    ierr=talsh_tensor_construct(A3, C8, (/nocc,nocc/), init_val=ZERO)
    
    !Diagram      0; Contraction 16; Tree Level  2; Scaling  2/ 0/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("A3(n1,m1)+=G2(n1,m1)", &
    A3,G2,scale=(-2.0d0,0.0d0))
    
    !Diagram      0; Contraction 17; Tree Level  2; Scaling  2/ 0/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("A3(n1,m1)+=F1(n1,m1)", &
    A3,F1,scale=(-2.0d0,0.0d0))
    
    !Diagram      0; Contraction 18; Tree Level  1; Scaling  3/ 3/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  1/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("Z1(e1,m1)+=T1(f1,n1)*M1(n1,e1,f1,m1)", &
    Z1,T1,M1,scale=(1.0d0,0.0d0))
    
    ierr=talsh_tensor_destruct(M1)
    
    !Diagram      0; Contraction 19; Tree Level  1; Scaling  3/ 5/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  1/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("Z1(e1,m1)+=V8(e1,n1,f1,d1)*T2(f1,d1,m1,n1)", &
    Z1,V8,T2,scale=(5.0d-1,0.0d0))
    
    !Diagram      0; Contraction 20; Tree Level  2; Scaling  4/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("A3(n1,m1)+=T1(d1,l1)*E2(n1,l1,d1,m1)", &
    A3,T1,E2,scale=(-2.0d0,0.0d0))
    
    ierr=talsh_tensor_destruct(E2)
    
    !Diagram      0; Contraction 21; Tree Level  2; Scaling  2/ 0/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("A3(n1,m1)+=A2(n1,m1)", &
    A3,A2,scale=(1.0d0,0.0d0))
    
    !Diagram      0; Contraction 22; Tree Level  1; Scaling  3/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  1/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("Z1(e1,m1)+=T1(e1,n1)*A3(n1,m1)", &
    Z1,T1,A3,scale=(5.0d-1,0.0d0))
    
    ierr=talsh_tensor_destruct(A3)
    
    ierr=talsh_tensor_construct(E3, C8, (/nvir,nvir/), init_val=ZERO)
    
    !Diagram      0; Contraction 23; Tree Level  3; Scaling  4/ 4/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  0/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("E3(f1,d1)+=V7(l1,m2,d1,e2)*T2(e2,f1,l1,m2)", &
    E3,V7,T2,scale=(1.0d0,0.0d0))
    
    !Diagram      0; Contraction 24; Tree Level  2; Scaling  0/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  0/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("I3(e1,f1)+=E3(e1,f1)", &
    I3,E3,scale=(1.0d0,0.0d0))
    
    !Diagram      0; Contraction 25; Tree Level  2; Scaling  0/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  0/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("I3(e1,f1)+=F4(e1,f1)", &
    I3,F4,scale=(2.0d0,0.0d0))
    
    !Diagram      0; Contraction 26; Tree Level  1; Scaling  1/ 3/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  1/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("Z1(e1,m1)+=T1(f1,m1)*I3(e1,f1)", &
    Z1,T1,I3,scale=(5.0d-1,0.0d0))
    
    ierr=talsh_tensor_destruct(I3)
    
    !Diagram      0; Contraction 27; Tree Level  1; Scaling  1/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  1/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("Z1(e1,m1)+=F2(e1,m1)", &
    Z1,F2,scale=(1.0d0,0.0d0))
    
    !ierr=talsh_tensor_destruct(F2)
    
    ierr=talsh_tensor_construct(M3, C8, (/nocc,nocc,nocc,nocc/), init_val=ZERO)
    
    !Diagram      0; Contraction 28; Tree Level  4; Scaling  4/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  4/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("M3(l1,m2,n1,m1)+=T1(e2,n1)*X1(l1,m2,e2,m1)", &
    M3,T1,X1,scale=(1.0d0,0.0d0))
    
    ierr=talsh_tensor_construct(X3, C8, (/nocc,nocc,nocc,nocc/), init_val=ZERO)
    
    !Diagram      0; Contraction 29; Tree Level  4; Scaling  4/ 4/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  4/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("X3(l1,m2,m1,n1)+=V7(l1,m2,d1,e2)*T2(d1,e2,m1,n1)", &
    X3,V7,T2,scale=(1.0d0,0.0d0))
    
    ierr=talsh_tensor_construct(Y3, C8, (/nocc,nvir/), init_val=ZERO)
    
    !Diagram      0; Contraction 30; Tree Level  4; Scaling  3/ 3/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  1/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("Y3(l1,e2)+=V7(l1,m2,d1,e2)*T1(d1,m2)", &
    Y3,V7,T1,scale=(1.0d0,0.0d0))
    
    !ierr=talsh_tensor_destruct(V7)
    
    ierr=talsh_tensor_construct(A4, C8, (/nvir,nvir,nocc,nocc/), init_val=ZERO)
    
    !Diagram      0; Contraction 31; Tree Level  2; Scaling  4/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("A4(f1,e1,m1,n1)+=F1(l1,m1)*T2(f1,e1,n1,l1)", &
    A4,F1,T2,scale=(1.0d0,0.0d0))
    
    !ierr=talsh_tensor_destruct(F1)
    
    !Diagram      0; Contraction 32; Tree Level  0; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("Z2(e1,f1,m1,n1)+=A4(f1,e1,m1,n1)", &
    Z2,A4,scale=(-1.0d0,0.0d0))
    
    !Diagram      0; Contraction 33; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("Z2(e1,f1,m1,n1)+=A4(f1,e1,n1,m1)", &
    Z2,A4,scale=(1.0d0,0.0d0))
    
    ierr=talsh_tensor_destruct(A4)
    
    ierr=talsh_tensor_construct(D4, C8, (/nvir,nvir,nocc,nocc/), init_val=ZERO)
    
    !Diagram      0; Contraction 34; Tree Level  2; Scaling  4/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("D4(e1,f1,n1,m1)+=T2(e1,f1,l1,n1)*G2(l1,m1)", &
    D4,T2,G2,scale=(1.0d0,0.0d0))
    
    ierr=talsh_tensor_destruct(G2)
    
    !Diagram      0; Contraction 35; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("Z2(e1,f1,m1,n1)+=D4(e1,f1,n1,m1)", &
    Z2,D4,scale=(-1.0d0,0.0d0))
    
    !Diagram      0; Contraction 36; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("Z2(e1,f1,m1,n1)+=D4(e1,f1,m1,n1)", &
    Z2,D4,scale=(1.0d0,0.0d0))
    
    ierr=talsh_tensor_destruct(D4)
    
    ierr=talsh_tensor_construct(E4, C8, (/nvir,nocc,nvir,nocc/), init_val=ZERO)
    
    !Diagram      0; Contraction 37; Tree Level  4; Scaling  2/ 4/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("E4(e1,l1,d1,n1)+=V8(e1,l1,d1,e2)*T1(e2,n1)", &
    E4,V8,T1,scale=(1.0d0,0.0d0))
    
    ierr=talsh_tensor_construct(G4, C8, (/nvir,nocc,nocc,nocc/), init_val=ZERO)
    
    !Diagram      0; Contraction 38; Tree Level  3; Scaling  3/ 5/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("G4(e1,l1,m1,n1)+=V8(e1,l1,d1,e2)*T2(d1,e2,m1,n1)", &
    G4,V8,T2,scale=(1.0d0,0.0d0))
    
    ierr=talsh_tensor_construct(I4, C8, (/nvir,nvir,nocc,nocc/), init_val=ZERO)
    
    !Diagram      0; Contraction 39; Tree Level  2; Scaling  2/ 4/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("I4(e1,f1,m1,n1)+=V6(e1,f1,m1,d1)*T1(d1,n1)", &
    I4,V6,T1,scale=(1.0d0,0.0d0))
    
    !ierr=talsh_tensor_destruct(V6)
    
    !Diagram      0; Contraction 40; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("Z2(e1,f1,m1,n1)+=I4(e1,f1,m1,n1)", &
    Z2,I4,scale=(1.0d0,0.0d0))
    
    !Diagram      0; Contraction 41; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("Z2(e1,f1,m1,n1)+=I4(e1,f1,n1,m1)", &
    Z2,I4,scale=(-1.0d0,0.0d0))
    
    ierr=talsh_tensor_destruct(I4)
    
    ierr=talsh_tensor_construct(J4, C8, (/nvir,nocc,nocc,nocc/), init_val=ZERO)
    
    !Diagram      0; Contraction 42; Tree Level  3; Scaling  3/ 3/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("J4(e1,l1,m1,n1)+=V5(e1,l1,m1,d1)*T1(d1,n1)", &
    J4,V5,T1,scale=(1.0d0,0.0d0))
    
    ierr=talsh_tensor_construct(M4, C8, (/nvir,nocc,nvir,nocc/), init_val=ZERO)
    
    !Diagram      0; Contraction 43; Tree Level  3; Scaling  2/ 4/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("M4(e1,l1,e2,m1)+=V8(e1,l1,d1,e2)*T1(d1,m1)", &
    M4,V8,T1,scale=(1.0d0,0.0d0))
    
    ierr=talsh_tensor_construct(X4, C8, (/nvir,nocc,nocc,nocc/), init_val=ZERO)
    
    !Diagram      0; Contraction 44; Tree Level  3; Scaling  3/ 3/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("X4(f1,l1,m1,n1)+=T2(e2,f1,m1,n1)*Y3(l1,e2)", &
    X4,T2,Y3,scale=(1.0d0,0.0d0))
    
    ierr=talsh_tensor_destruct(Y3)
    
    ierr=talsh_tensor_construct(Y4, C8, (/nvir,nvir,nocc,nocc/), init_val=ZERO)
    
    !Diagram      0; Contraction 45; Tree Level  2; Scaling  2/ 4/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("Y4(e1,f1,m1,n1)+=T2(e1,d1,m1,n1)*E3(f1,d1)", &
    Y4,T2,E3,scale=(1.0d0,0.0d0))
    
    ierr=talsh_tensor_destruct(E3)
    
    !Diagram      0; Contraction 46; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("Z2(e1,f1,m1,n1)+=Y4(e1,f1,m1,n1)", &
    Z2,Y4,scale=(5.0d-1,0.0d0))
    
    !Diagram      0; Contraction 47; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("Z2(e1,f1,m1,n1)+=Y4(f1,e1,m1,n1)", &
    Z2,Y4,scale=(-5.0d-1,0.0d0))
    
    ierr=talsh_tensor_destruct(Y4)
    
    ierr=talsh_tensor_construct(M6, C8, (/nocc,nocc,nocc,nocc/), init_val=ZERO)
    
    !Diagram      0; Contraction 48; Tree Level  3; Scaling  4/ 0/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  4/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("M6(m2,l1,n1,m1)+=V1(l1,m2,m1,n1)", &
    M6,V1,scale=(1.0d0,0.0d0))
    
    !Diagram      0; Contraction 49; Tree Level  3; Scaling  4/ 0/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  4/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("M6(m2,l1,n1,m1)+=V1(m2,l1,m1,n1)", &
    M6,V1,scale=(-1.0d0,0.0d0))
    
    ierr=talsh_tensor_construct(D5, C8, (/nvir,nvir/), init_val=ZERO)
    
    !Diagram      0; Contraction 50; Tree Level  3; Scaling  2/ 4/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  0/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("D5(e1,e2)+=V8(e1,l1,d1,e2)*T1(d1,l1)", &
    D5,V8,T1,scale=(1.0d0,0.0d0))
    
    !ierr=talsh_tensor_destruct(V8)
    
    ierr=talsh_tensor_construct(E5, C8, (/nvir,nvir,nocc,nocc/), init_val=ZERO)
    
    !Diagram      0; Contraction 51; Tree Level  2; Scaling  2/ 4/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("E5(e1,f1,n1,m1)+=F4(e1,d1)*T2(f1,d1,n1,m1)", &
    E5,F4,T2,scale=(1.0d0,0.0d0))
    
    !ierr=talsh_tensor_destruct(F4)
    
    !Diagram      0; Contraction 52; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("Z2(e1,f1,m1,n1)+=E5(e1,f1,n1,m1)", &
    Z2,E5,scale=(1.0d0,0.0d0))
    
    !Diagram      0; Contraction 53; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("Z2(e1,f1,m1,n1)+=E5(f1,e1,n1,m1)", &
    Z2,E5,scale=(-1.0d0,0.0d0))
    
    ierr=talsh_tensor_destruct(E5)
    
    ierr=talsh_tensor_construct(G5, C8, (/nvir,nvir,nocc,nocc/), init_val=ZERO)
    
    !Diagram      0; Contraction 54; Tree Level  2; Scaling  4/ 4/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("G5(f1,e1,n1,m1)+=T2(e2,f1,l1,n1)*M4(e1,l1,e2,m1)", &
    G5,T2,M4,scale=(1.0d0,0.0d0))
    
    ierr=talsh_tensor_destruct(M4)
    
    !Diagram      0; Contraction 55; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("Z2(e1,f1,m1,n1)+=G5(f1,e1,n1,m1)", &
    Z2,G5,scale=(1.0d0,0.0d0))
    
    !Diagram      0; Contraction 56; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("Z2(e1,f1,m1,n1)+=G5(e1,f1,n1,m1)", &
    Z2,G5,scale=(-1.0d0,0.0d0))
    
    !Diagram      0; Contraction 57; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("Z2(e1,f1,m1,n1)+=G5(f1,e1,m1,n1)", &
    Z2,G5,scale=(-1.0d0,0.0d0))
    
    !Diagram      0; Contraction 58; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("Z2(e1,f1,m1,n1)+=G5(e1,f1,m1,n1)", &
    Z2,G5,scale=(1.0d0,0.0d0))
    
    ierr=talsh_tensor_destruct(G5)
    
    ierr=talsh_tensor_construct(I5, C8, (/nvir,nocc,nocc,nocc/), init_val=ZERO)
    
    !Diagram      0; Contraction 59; Tree Level  3; Scaling  5/ 3/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("I5(f1,l1,n1,m1)+=T2(e2,f1,m2,n1)*X1(l1,m2,e2,m1)", &
    I5,T2,X1,scale=(1.0d0,0.0d0))
    
    ierr=talsh_tensor_construct(J5, C8, (/nocc,nvir,nocc,nocc/), init_val=ZERO)
    
    !Diagram      0; Contraction 60; Tree Level  3; Scaling  3/ 3/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("J5(l1,f1,m1,n1)+=F3(l1,d1)*T2(d1,f1,m1,n1)", &
    J5,F3,T2,scale=(1.0d0,0.0d0))
    
    !ierr=talsh_tensor_destruct(F3)
    
    ierr=talsh_tensor_construct(M5, C8, (/nvir,nvir,nvir,nocc/), init_val=ZERO)
    
    !Diagram      0; Contraction 61; Tree Level  3; Scaling  1/ 5/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  1/ 3/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("M5(e1,f1,d1,n1)+=V9(e1,f1,d1,e2)*T1(e2,n1)", &
    M5,V9,T1,scale=(1.0d0,0.0d0))
    
    ierr=talsh_tensor_construct(X5, C8, (/nvir,nvir,nocc,nocc/), init_val=ZERO)
    
    !Diagram      0; Contraction 62; Tree Level  2; Scaling  2/ 4/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("X5(e1,f1,m1,n1)+=T1(d1,m1)*M5(e1,f1,d1,n1)", &
    X5,T1,M5,scale=(1.0d0,0.0d0))
    
    ierr=talsh_tensor_destruct(M5)
    
    !Diagram      0; Contraction 63; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("Z2(e1,f1,m1,n1)+=X5(e1,f1,m1,n1)", &
    Z2,X5,scale=(5.0d-1,0.0d0))
    
    !Diagram      0; Contraction 64; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("Z2(e1,f1,m1,n1)+=X5(e1,f1,n1,m1)", &
    Z2,X5,scale=(-5.0d-1,0.0d0))
    
    ierr=talsh_tensor_destruct(X5)
    
    ierr=talsh_tensor_construct(Y5, C8, (/nvir,nvir,nocc,nocc/), init_val=ZERO)
    
    !Diagram      0; Contraction 65; Tree Level  2; Scaling  4/ 4/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("Y5(e1,f1,m1,n1)+=V5(e1,l1,m1,d1)*T2(f1,d1,n1,l1)", &
    Y5,V5,T2,scale=(1.0d0,0.0d0))
    
    !ierr=talsh_tensor_destruct(V5)
    
    !Diagram      0; Contraction 66; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("Z2(e1,f1,m1,n1)+=Y5(e1,f1,m1,n1)", &
    Z2,Y5,scale=(1.0d0,0.0d0))
    
    !Diagram      0; Contraction 67; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("Z2(e1,f1,m1,n1)+=Y5(f1,e1,m1,n1)", &
    Z2,Y5,scale=(-1.0d0,0.0d0))
    
    !Diagram      0; Contraction 68; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("Z2(e1,f1,m1,n1)+=Y5(e1,f1,n1,m1)", &
    Z2,Y5,scale=(-1.0d0,0.0d0))
    
    !Diagram      0; Contraction 69; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("Z2(e1,f1,m1,n1)+=Y5(f1,e1,n1,m1)", &
    Z2,Y5,scale=(1.0d0,0.0d0))
    
    ierr=talsh_tensor_destruct(Y5)
    
    ierr=talsh_tensor_construct(A6, C8, (/nocc,nocc,nocc,nocc/), init_val=ZERO)
    
    !Diagram      0; Contraction 70; Tree Level  4; Scaling  4/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  4/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("A6(l1,m2,m1,n1)+=V4(l1,m2,m1,d1)*T1(d1,n1)", &
    A6,V4,T1,scale=(1.0d0,0.0d0))
    
    ierr=talsh_tensor_construct(X10, C8, (/nocc,nocc,nocc,nocc/), init_val=ZERO)
    
    !Diagram      0; Contraction 71; Tree Level  2; Scaling  4/ 0/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  4/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("X10(l1,m2,m1,n1)+=A6(l1,m2,m1,n1)", &
    X10,A6,scale=(2.0d0,0.0d0))
    
    !Diagram      0; Contraction 72; Tree Level  2; Scaling  4/ 0/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  4/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("X10(l1,m2,m1,n1)+=A6(l1,m2,n1,m1)", &
    X10,A6,scale=(-2.0d0,0.0d0))
    
    ierr=talsh_tensor_construct(A11, C8, (/nocc,nocc,nocc,nocc/), init_val=ZERO)
    
    !Diagram      0; Contraction 73; Tree Level  3; Scaling  4/ 0/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  4/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("A11(m2,l1,n1,m1)+=M3(l1,m2,n1,m1)", &
    A11,M3,scale=(-1.0d0,0.0d0))
    
    !Diagram      0; Contraction 74; Tree Level  3; Scaling  4/ 0/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  4/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("A11(m2,l1,n1,m1)+=A6(l1,m2,m1,n1)", &
    A11,A6,scale=(-2.0d0,0.0d0))
    
    !Diagram      0; Contraction 75; Tree Level  3; Scaling  4/ 0/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  4/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("A11(m2,l1,n1,m1)+=M3(l1,m2,m1,n1)", &
    A11,M3,scale=(1.0d0,0.0d0))
    
    !Diagram      0; Contraction 76; Tree Level  3; Scaling  4/ 0/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  4/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("M6(m2,l1,n1,m1)+=A6(m2,l1,m1,n1)", &
    M6,A6,scale=(-1.0d0,0.0d0))
    
    !Diagram      0; Contraction 77; Tree Level  3; Scaling  4/ 0/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  4/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("M6(m2,l1,n1,m1)+=A6(l1,m2,n1,m1)", &
    M6,A6,scale=(-1.0d0,0.0d0))
    
    !Diagram      0; Contraction 78; Tree Level  3; Scaling  4/ 0/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  4/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("M6(m2,l1,n1,m1)+=A6(m2,l1,n1,m1)", &
    M6,A6,scale=(1.0d0,0.0d0))
    
    ierr=talsh_tensor_destruct(A6)
    
    ierr=talsh_tensor_construct(X6, C8, (/nocc,nvir,nocc,nocc/), init_val=ZERO)
    
    !Diagram      0; Contraction 79; Tree Level  3; Scaling  5/ 3/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("X6(l1,f1,m1,n1)+=V4(l1,m2,m1,d1)*T2(d1,f1,m2,n1)", &
    X6,V4,T2,scale=(1.0d0,0.0d0))
    
    ierr=talsh_tensor_construct(E10, C8, (/nvir,nocc,nocc,nocc/), init_val=ZERO)
    
    !Diagram      0; Contraction 80; Tree Level  2; Scaling  3/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("E10(e1,l1,m1,n1)+=X6(l1,e1,m1,n1)", &
    E10,X6,scale=(-4.0d0,0.0d0))
    
    !Diagram      0; Contraction 81; Tree Level  2; Scaling  3/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("E10(e1,l1,m1,n1)+=X6(l1,e1,n1,m1)", &
    E10,X6,scale=(4.0d0,0.0d0))
    
    ierr=talsh_tensor_construct(A7, C8, (/nvir,nvir,nocc,nocc/), init_val=ZERO)
    
    !Diagram      0; Contraction 82; Tree Level  2; Scaling  4/ 4/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("A7(e1,f1,m1,n1)+=T2(e1,d1,m1,l1)*J1(l1,f1,d1,n1)", &
    A7,T2,J1,scale=(1.0d0,0.0d0))
    
    ierr=talsh_tensor_destruct(J1)
    
    !Diagram      0; Contraction 83; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("Z2(e1,f1,m1,n1)+=A7(e1,f1,m1,n1)", &
    Z2,A7,scale=(5.0d-1,0.0d0))
    
    !Diagram      0; Contraction 84; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("Z2(e1,f1,m1,n1)+=A7(f1,e1,m1,n1)", &
    Z2,A7,scale=(-5.0d-1,0.0d0))
    
    !Diagram      0; Contraction 85; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("Z2(e1,f1,m1,n1)+=A7(e1,f1,n1,m1)", &
    Z2,A7,scale=(-5.0d-1,0.0d0))
    
    !Diagram      0; Contraction 86; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("Z2(e1,f1,m1,n1)+=A7(f1,e1,n1,m1)", &
    Z2,A7,scale=(5.0d-1,0.0d0))
    
    ierr=talsh_tensor_destruct(A7)
    
    ierr=talsh_tensor_construct(M11, C8, (/nvir,nocc,nocc,nocc/), init_val=ZERO)
    
    !Diagram      0; Contraction 87; Tree Level  2; Scaling  3/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("M11(f1,l1,m1,n1)+=J4(f1,l1,m1,n1)", &
    M11,J4,scale=(4.0d0,0.0d0))
    
    !Diagram      0; Contraction 88; Tree Level  2; Scaling  3/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("M11(f1,l1,m1,n1)+=J4(f1,l1,n1,m1)", &
    M11,J4,scale=(-4.0d0,0.0d0))
    
    !Diagram      0; Contraction 89; Tree Level  2; Scaling  3/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("E10(e1,l1,m1,n1)+=J5(l1,e1,m1,n1)", &
    E10,J5,scale=(-4.0d0,0.0d0))
    
    !Diagram      0; Contraction 90; Tree Level  2; Scaling  3/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("E10(e1,l1,m1,n1)+=X4(e1,l1,m1,n1)", &
    E10,X4,scale=(4.0d0,0.0d0))
    
    ierr=talsh_tensor_construct(G7, C8, (/nvir,nvir,nocc,nocc/), init_val=ZERO)
    
    !Diagram      0; Contraction 91; Tree Level  2; Scaling  4/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("G7(e1,f1,m1,n1)+=T2(e1,f1,m1,l1)*A2(l1,n1)", &
    G7,T2,A2,scale=(1.0d0,0.0d0))
    
    ierr=talsh_tensor_destruct(A2)
    
    !Diagram      0; Contraction 92; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("Z2(e1,f1,m1,n1)+=G7(e1,f1,m1,n1)", &
    Z2,G7,scale=(5.0d-1,0.0d0))
    
    !Diagram      0; Contraction 93; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("Z2(e1,f1,m1,n1)+=G7(e1,f1,n1,m1)", &
    Z2,G7,scale=(-5.0d-1,0.0d0))
    
    ierr=talsh_tensor_destruct(G7)
    
    !Diagram      0; Contraction 94; Tree Level  2; Scaling  3/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("E10(e1,l1,m1,n1)+=I5(e1,l1,n1,m1)", &
    E10,I5,scale=(-4.0d0,0.0d0))
    
    !Diagram      0; Contraction 95; Tree Level  2; Scaling  3/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("E10(e1,l1,m1,n1)+=I5(e1,l1,m1,n1)", &
    E10,I5,scale=(4.0d0,0.0d0))
    
    ierr=talsh_tensor_construct(J7, C8, (/nocc,nocc/), init_val=ZERO)
    
    !Diagram      0; Contraction 96; Tree Level  3; Scaling  4/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("J7(m2,m1)+=T1(e2,l1)*X1(l1,m2,e2,m1)", &
    J7,T1,X1,scale=(1.0d0,0.0d0))
    
    ierr=talsh_tensor_destruct(X1)
    
    ierr=talsh_tensor_construct(M7, C8, (/nvir,nvir,nocc,nocc/), init_val=ZERO)
    
    !Diagram      0; Contraction 97; Tree Level  2; Scaling  4/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("M7(e1,f1,n1,m1)+=T2(e1,f1,m2,n1)*J7(m2,m1)", &
    M7,T2,J7,scale=(1.0d0,0.0d0))
    
    ierr=talsh_tensor_destruct(J7)
    
    !Diagram      0; Contraction 98; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("Z2(e1,f1,m1,n1)+=M7(e1,f1,n1,m1)", &
    Z2,M7,scale=(1.0d0,0.0d0))
    
    !Diagram      0; Contraction 99; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("Z2(e1,f1,m1,n1)+=M7(e1,f1,m1,n1)", &
    Z2,M7,scale=(-1.0d0,0.0d0))
    
    ierr=talsh_tensor_destruct(M7)
    
    ierr=talsh_tensor_construct(X7, C8, (/nvir,nvir,nocc,nocc/), init_val=ZERO)
    
    !Diagram      0; Contraction 100; Tree Level  2; Scaling  2/ 4/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("X7(f1,e1,m1,n1)+=T2(e2,f1,m1,n1)*D5(e1,e2)", &
    X7,T2,D5,scale=(1.0d0,0.0d0))
    
    ierr=talsh_tensor_destruct(D5)
    
    !Diagram      0; Contraction 101; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("Z2(e1,f1,m1,n1)+=X7(f1,e1,m1,n1)", &
    Z2,X7,scale=(-1.0d0,0.0d0))
    
    !Diagram      0; Contraction 102; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("Z2(e1,f1,m1,n1)+=X7(e1,f1,m1,n1)", &
    Z2,X7,scale=(1.0d0,0.0d0))
    
    ierr=talsh_tensor_destruct(X7)
    
    ierr=talsh_tensor_construct(Y7, C8, (/nocc,nocc/), init_val=ZERO)
    
    !Diagram      0; Contraction 103; Tree Level  3; Scaling  4/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("Y7(m2,m1)+=V4(l1,m2,m1,d1)*T1(d1,l1)", &
    Y7,V4,T1,scale=(1.0d0,0.0d0))
    
    !ierr=talsh_tensor_destruct(V4)
    
    ierr=talsh_tensor_construct(A8, C8, (/nvir,nvir,nocc,nocc/), init_val=ZERO)
    
    !Diagram      0; Contraction 104; Tree Level  2; Scaling  4/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("A8(e1,f1,n1,m1)+=T2(e1,f1,m2,n1)*Y7(m2,m1)", &
    A8,T2,Y7,scale=(1.0d0,0.0d0))
    
    ierr=talsh_tensor_destruct(Y7)
    
    !Diagram      0; Contraction 105; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("Z2(e1,f1,m1,n1)+=A8(e1,f1,n1,m1)", &
    Z2,A8,scale=(1.0d0,0.0d0))
    
    !Diagram      0; Contraction 106; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("Z2(e1,f1,m1,n1)+=A8(e1,f1,m1,n1)", &
    Z2,A8,scale=(-1.0d0,0.0d0))
    
    ierr=talsh_tensor_destruct(A8)
    
    ierr=talsh_tensor_construct(D8, C8, (/nocc,nocc,nocc,nocc/), init_val=ZERO)
    
    !Diagram      0; Contraction 107; Tree Level  3; Scaling  4/ 0/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  4/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("D8(l1,m2,m1,n1)+=X3(l1,m2,m1,n1)", &
    D8,X3,scale=(1.0d0,0.0d0))
    
    !Diagram      0; Contraction 108; Tree Level  3; Scaling  4/ 0/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  4/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("D8(l1,m2,m1,n1)+=X3(m2,l1,m1,n1)", &
    D8,X3,scale=(-1.0d0,0.0d0))
    
    !Diagram      0; Contraction 109; Tree Level  2; Scaling  5/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("E10(e1,l1,m1,n1)+=T1(e1,m2)*D8(m2,l1,m1,n1)", &
    E10,T1,D8,scale=(-1.0d0,0.0d0))
    
    ierr=talsh_tensor_destruct(D8)
    
    !Diagram      0; Contraction 110; Tree Level  2; Scaling  3/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("E10(e1,l1,m1,n1)+=J4(e1,l1,m1,n1)", &
    E10,J4,scale=(4.0d0,0.0d0))
    
    !Diagram      0; Contraction 111; Tree Level  2; Scaling  3/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("E10(e1,l1,m1,n1)+=J4(e1,l1,n1,m1)", &
    E10,J4,scale=(-4.0d0,0.0d0))
    
    ierr=talsh_tensor_destruct(J4)
    
    ierr=talsh_tensor_construct(J8, C8, (/nvir,nocc,nocc,nocc/), init_val=ZERO)
    
    !Diagram      0; Contraction 112; Tree Level  3; Scaling  3/ 3/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("J8(e1,l1,m1,n1)+=T1(d1,m1)*E4(e1,l1,d1,n1)", &
    J8,T1,E4,scale=(1.0d0,0.0d0))
    
    ierr=talsh_tensor_destruct(E4)
    
    !Diagram      0; Contraction 113; Tree Level  2; Scaling  3/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("E10(e1,l1,m1,n1)+=J8(e1,l1,m1,n1)", &
    E10,J8,scale=(2.0d0,0.0d0))
    
    !Diagram      0; Contraction 114; Tree Level  2; Scaling  3/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("E10(e1,l1,m1,n1)+=J8(e1,l1,n1,m1)", &
    E10,J8,scale=(-2.0d0,0.0d0))
    
    !Diagram      0; Contraction 115; Tree Level  2; Scaling  3/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("E10(e1,l1,m1,n1)+=G4(e1,l1,m1,n1)", &
    E10,G4,scale=(2.0d0,0.0d0))
    
    !Diagram      0; Contraction 116; Tree Level  2; Scaling  3/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("M11(f1,l1,m1,n1)+=J8(f1,l1,m1,n1)", &
    M11,J8,scale=(2.0d0,0.0d0))
    
    !Diagram      0; Contraction 117; Tree Level  2; Scaling  3/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("M11(f1,l1,m1,n1)+=J8(f1,l1,n1,m1)", &
    M11,J8,scale=(-2.0d0,0.0d0))
    
    ierr=talsh_tensor_destruct(J8)
    
    !Diagram      0; Contraction 118; Tree Level  2; Scaling  3/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("M11(f1,l1,m1,n1)+=I5(f1,l1,n1,m1)", &
    M11,I5,scale=(-4.0d0,0.0d0))
    
    !Diagram      0; Contraction 119; Tree Level  2; Scaling  3/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("M11(f1,l1,m1,n1)+=I5(f1,l1,m1,n1)", &
    M11,I5,scale=(4.0d0,0.0d0))
    
    ierr=talsh_tensor_destruct(I5)
    
    !Diagram      0; Contraction 120; Tree Level  2; Scaling  3/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("M11(f1,l1,m1,n1)+=X6(l1,f1,m1,n1)", &
    M11,X6,scale=(-4.0d0,0.0d0))
    
    !Diagram      0; Contraction 121; Tree Level  2; Scaling  3/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("M11(f1,l1,m1,n1)+=X6(l1,f1,n1,m1)", &
    M11,X6,scale=(4.0d0,0.0d0))
    
    ierr=talsh_tensor_destruct(X6)
    
    !Diagram      0; Contraction 122; Tree Level  2; Scaling  3/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("M11(f1,l1,m1,n1)+=G4(f1,l1,m1,n1)", &
    M11,G4,scale=(2.0d0,0.0d0))
    
    ierr=talsh_tensor_destruct(G4)
    
    !Diagram      0; Contraction 123; Tree Level  2; Scaling  5/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("E10(e1,l1,m1,n1)+=T1(e1,m2)*M6(l1,m2,n1,m1)", &
    E10,T1,M6,scale=(-2.0d0,0.0d0))
    
    ierr=talsh_tensor_destruct(M6)
    
    !Diagram      0; Contraction 124; Tree Level  2; Scaling  3/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("E10(e1,l1,m1,n1)+=V2(e1,l1,m1,n1)", &
    E10,V2,scale=(4.0d0,0.0d0))
    
    !Diagram      0; Contraction 125; Tree Level  1; Scaling  4/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("Z2(e1,f1,m1,n1)+=T1(f1,l1)*E10(e1,l1,m1,n1)", &
    Z2,T1,E10,scale=(-2.5d-1,0.0d0))
    
    ierr=talsh_tensor_destruct(E10)
    
    ierr=talsh_tensor_construct(I10, C8, (/nocc,nocc,nocc,nocc/), init_val=ZERO)
    
    !Diagram      0; Contraction 126; Tree Level  3; Scaling  4/ 0/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  4/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("I10(l1,m2,n1,m1)+=M3(l1,m2,n1,m1)", &
    I10,M3,scale=(1.0d0,0.0d0))
    
    !Diagram      0; Contraction 127; Tree Level  3; Scaling  4/ 0/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  4/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("I10(l1,m2,n1,m1)+=M3(l1,m2,m1,n1)", &
    I10,M3,scale=(-1.0d0,0.0d0))
    
    ierr=talsh_tensor_destruct(M3)
    
    !Diagram      0; Contraction 128; Tree Level  2; Scaling  4/ 0/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  4/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("X10(l1,m2,m1,n1)+=I10(l1,m2,n1,m1)", &
    X10,I10,scale=(1.0d0,0.0d0))
    
    !Diagram      0; Contraction 129; Tree Level  2; Scaling  4/ 0/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  4/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("X10(l1,m2,m1,n1)+=X3(l1,m2,m1,n1)", &
    X10,X3,scale=(1.0d0,0.0d0))
    
    ierr=talsh_tensor_destruct(X3)
    
    !Diagram      0; Contraction 130; Tree Level  2; Scaling  4/ 0/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  4/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("X10(l1,m2,m1,n1)+=V1(l1,m2,m1,n1)", &
    X10,V1,scale=(2.0d0,0.0d0))
    
    !ierr=talsh_tensor_destruct(V1)
    
    !Diagram      0; Contraction 131; Tree Level  1; Scaling  6/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("Z2(e1,f1,m1,n1)+=T2(e1,f1,l1,m2)*X10(l1,m2,m1,n1)", &
    Z2,T2,X10,scale=(2.5d-1,0.0d0))
    
    ierr=talsh_tensor_destruct(X10)
    
    !Diagram      0; Contraction 132; Tree Level  3; Scaling  4/ 0/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  4/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("A11(m2,l1,n1,m1)+=I10(m2,l1,n1,m1)", &
    A11,I10,scale=(1.0d0,0.0d0))
    
    ierr=talsh_tensor_destruct(I10)
    
    !Diagram      0; Contraction 133; Tree Level  2; Scaling  5/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("M11(f1,l1,m1,n1)+=T1(f1,m2)*A11(m2,l1,n1,m1)", &
    M11,T1,A11,scale=(-1.0d0,0.0d0))
    
    ierr=talsh_tensor_destruct(A11)
    
    !Diagram      0; Contraction 134; Tree Level  2; Scaling  3/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("M11(f1,l1,m1,n1)+=X4(f1,l1,m1,n1)", &
    M11,X4,scale=(4.0d0,0.0d0))
    
    ierr=talsh_tensor_destruct(X4)
    
    !Diagram      0; Contraction 135; Tree Level  2; Scaling  3/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("M11(f1,l1,m1,n1)+=J5(l1,f1,m1,n1)", &
    M11,J5,scale=(-4.0d0,0.0d0))
    
    ierr=talsh_tensor_destruct(J5)
    
    !Diagram      0; Contraction 136; Tree Level  2; Scaling  3/ 1/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  3/ 1/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("M11(f1,l1,m1,n1)+=V2(f1,l1,m1,n1)", &
    M11,V2,scale=(4.0d0,0.0d0))
    
    !ierr=talsh_tensor_destruct(V2)
    
    !Diagram      0; Contraction 137; Tree Level  1; Scaling  4/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("Z2(e1,f1,m1,n1)+=T1(e1,l1)*M11(f1,l1,m1,n1)", &
    Z2,T1,M11,scale=(2.5d-1,0.0d0))
    
    ierr=talsh_tensor_destruct(M11)
    
    !ierr=talsh_tensor_destruct(T1)
    
    !Diagram      0; Contraction 138; Tree Level  1; Scaling  2/ 6/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("Z2(e1,f1,m1,n1)+=V9(e1,f1,d1,e2)*T2(d1,e2,m1,n1)", &
    Z2,V9,T2,scale=(5.0d-1,0.0d0))
    
    !ierr=talsh_tensor_destruct(T2)
    
    !ierr=talsh_tensor_destruct(V9)
    
    !Diagram      0; Contraction 139; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("Z2(e1,f1,m1,n1)+=V3(e1,f1,m1,n1)", &
    Z2,V3,scale=(1.0d0,0.0d0))
    
    !ierr=talsh_tensor_destruct(V3)
    
    
end subroutine talsh_tenpi_ccsd
