!
! CCD_T6 generated by Jan Brandejs.
!

subroutine talsh_tenpi_ccd(nocc,nvir,F1,F4,T2,V1,V7, &
        V5,V3,V9,Z0,Z2)
    
    use talsh
    use tensor_algebra
    use, intrinsic:: ISO_C_BINDING
    
    implicit none
    
    complex(8), parameter :: ZERO=(0.D0,0.D0),ONE_HALF=(0.5D0,0.D0), &
                             MINUS_ONE=(-1.D0,0.D0),ONE=(1.0D0,0.D0), MINUS_ONE_HALF=(-0.5D0,0.D0), &
                             MINUS_ONE_QUARTER=(-0.25D0,0.D0), ONE_QUARTER=(0.25D0,0.D0), &
                             MINUS_ONE_EIGHT=(-0.125D0,0.D0)
    
    
    integer, intent(in) :: nocc
    integer, intent(in) :: nvir
    type(talsh_tens_t), intent(inout) :: F1    !       OO
    type(talsh_tens_t), intent(inout) :: F4    !       VV
    type(talsh_tens_t), intent(inout) :: T2    !       VVOO
    type(talsh_tens_t), intent(inout) :: V1    !       OOOO
    type(talsh_tens_t), intent(inout) :: V7    !       OOVV
    type(talsh_tens_t), intent(inout) :: V5    !       VOOV
    type(talsh_tens_t), intent(inout) :: V3    !       VVOO
    type(talsh_tens_t), intent(inout) :: V9    !       VVVV
    type(talsh_tens_t), intent(inout) :: Z0    !       UnitTensor
    type(talsh_tens_t), intent(inout) :: Z2    !       VVOO
    type(talsh_tens_t) :: E1    !       OO
    type(talsh_tens_t) :: G1    !       VVOO
    type(talsh_tens_t) :: I1    !       VVOO
    type(talsh_tens_t) :: J1    !       VVOO
    type(talsh_tens_t) :: X1    !       OOOO
    type(talsh_tens_t) :: A2    !       OVVO
    type(talsh_tens_t) :: D2    !       VVOO
    type(talsh_tens_t) :: E2    !       VVOO
    type(talsh_tens_t) :: G2    !       VV
    type(talsh_tens_t) :: I2    !       VVOO
    
    integer :: ierr
    
    write(*,*) "    Running code generated by tenpi.   "
    
    !Diagram      0; Contraction 1; Tree Level  0; Scaling  4/ 4/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  0/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("Z0()+=V7(m1,n1,e1,f1)*T2(e1,f1,m1,n1)", &
    Z0,V7,T2,scale=(2.5d-1,0.0d0))
    
    !Diagram      0; Contraction 2; Tree Level  0; Scaling  2/ 6/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("Z2(e1,f1,m1,n1)+=V9(e1,f1,d1,e2)*T2(d1,e2,m1,n1)", &
    Z2,V9,T2,scale=(5.0d-1,0.0d0))
    
    !ierr=talsh_tensor_destruct(V9)
    
    ierr=talsh_tensor_construct(E1, C8, (/nocc,nocc/), init_val=ZERO)
    
    !Diagram      0; Contraction 3; Tree Level  3; Scaling  4/ 4/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("E1(l1,n1)+=V7(l1,m2,d1,e2)*T2(d1,e2,m2,n1)", &
    E1,V7,T2,scale=(1.0d0,0.0d0))
    
    ierr=talsh_tensor_construct(G1, C8, (/nvir,nvir,nocc,nocc/), init_val=ZERO)
    
    !Diagram      0; Contraction 4; Tree Level  2; Scaling  4/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("G1(e1,f1,m1,n1)+=T2(e1,f1,m1,l1)*E1(l1,n1)", &
    G1,T2,E1,scale=(1.0d0,0.0d0))
    
    ierr=talsh_tensor_destruct(E1)
    
    !Diagram      0; Contraction 5; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("Z2(e1,f1,m1,n1)+=G1(e1,f1,m1,n1)", &
    Z2,G1,scale=(5.0d-1,0.0d0))
    
    !Diagram      0; Contraction 6; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("Z2(e1,f1,m1,n1)+=G1(e1,f1,n1,m1)", &
    Z2,G1,scale=(-5.0d-1,0.0d0))
    
    ierr=talsh_tensor_destruct(G1)
    
    ierr=talsh_tensor_construct(I1, C8, (/nvir,nvir,nocc,nocc/), init_val=ZERO)
    
    !Diagram      0; Contraction 7; Tree Level  2; Scaling  4/ 4/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("I1(e1,f1,m1,n1)+=V5(e1,l1,m1,d1)*T2(f1,d1,n1,l1)", &
    I1,V5,T2,scale=(1.0d0,0.0d0))
    
    !ierr=talsh_tensor_destruct(V5)
    
    !Diagram      0; Contraction 8; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("Z2(e1,f1,m1,n1)+=I1(e1,f1,m1,n1)", &
    Z2,I1,scale=(1.0d0,0.0d0))
    
    !Diagram      0; Contraction 9; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("Z2(e1,f1,m1,n1)+=I1(f1,e1,m1,n1)", &
    Z2,I1,scale=(-1.0d0,0.0d0))
    
    !Diagram      0; Contraction 10; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("Z2(e1,f1,m1,n1)+=I1(e1,f1,n1,m1)", &
    Z2,I1,scale=(-1.0d0,0.0d0))
    
    !Diagram      0; Contraction 11; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("Z2(e1,f1,m1,n1)+=I1(f1,e1,n1,m1)", &
    Z2,I1,scale=(1.0d0,0.0d0))
    
    ierr=talsh_tensor_destruct(I1)
    
    ierr=talsh_tensor_construct(J1, C8, (/nvir,nvir,nocc,nocc/), init_val=ZERO)
    
    !Diagram      0; Contraction 12; Tree Level  2; Scaling  4/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("J1(f1,e1,m1,n1)+=F1(l1,m1)*T2(f1,e1,n1,l1)", &
    J1,F1,T2,scale=(1.0d0,0.0d0))
    
    !ierr=talsh_tensor_destruct(F1)
    
    !Diagram      0; Contraction 13; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("Z2(e1,f1,m1,n1)+=J1(f1,e1,m1,n1)", &
    Z2,J1,scale=(-1.0d0,0.0d0))
    
    !Diagram      0; Contraction 14; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("Z2(e1,f1,m1,n1)+=J1(f1,e1,n1,m1)", &
    Z2,J1,scale=(1.0d0,0.0d0))
    
    ierr=talsh_tensor_destruct(J1)
    
    ierr=talsh_tensor_construct(X1, C8, (/nocc,nocc,nocc,nocc/), init_val=ZERO)
    
    !Diagram      0; Contraction 15; Tree Level  2; Scaling  4/ 4/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  4/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("X1(l1,m2,m1,n1)+=V7(l1,m2,d1,e2)*T2(d1,e2,m1,n1)", &
    X1,V7,T2,scale=(1.0d0,0.0d0))
    
    !Diagram      0; Contraction 16; Tree Level  2; Scaling  4/ 0/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  4/ 0/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("X1(l1,m2,m1,n1)+=V1(l1,m2,m1,n1)", &
    X1,V1,scale=(2.0d0,0.0d0))
    
    !ierr=talsh_tensor_destruct(V1)
    
    !Diagram      0; Contraction 17; Tree Level  1; Scaling  6/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("Z2(e1,f1,m1,n1)+=T2(e1,f1,l1,m2)*X1(l1,m2,m1,n1)", &
    Z2,T2,X1,scale=(2.5d-1,0.0d0))
    
    ierr=talsh_tensor_destruct(X1)
    
    ierr=talsh_tensor_construct(A2, C8, (/nocc,nvir,nvir,nocc/), init_val=ZERO)
    
    !Diagram      0; Contraction 18; Tree Level  3; Scaling  4/ 4/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("A2(l1,f1,d1,n1)+=V7(l1,m2,d1,e2)*T2(e2,f1,m2,n1)", &
    A2,V7,T2,scale=(1.0d0,0.0d0))
    
    ierr=talsh_tensor_construct(D2, C8, (/nvir,nvir,nocc,nocc/), init_val=ZERO)
    
    !Diagram      0; Contraction 19; Tree Level  2; Scaling  4/ 4/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("D2(e1,f1,m1,n1)+=T2(e1,d1,m1,l1)*A2(l1,f1,d1,n1)", &
    D2,T2,A2,scale=(1.0d0,0.0d0))
    
    ierr=talsh_tensor_destruct(A2)
    
    !Diagram      0; Contraction 20; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("Z2(e1,f1,m1,n1)+=D2(e1,f1,m1,n1)", &
    Z2,D2,scale=(5.0d-1,0.0d0))
    
    !Diagram      0; Contraction 21; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("Z2(e1,f1,m1,n1)+=D2(f1,e1,m1,n1)", &
    Z2,D2,scale=(-5.0d-1,0.0d0))
    
    !Diagram      0; Contraction 22; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("Z2(e1,f1,m1,n1)+=D2(e1,f1,n1,m1)", &
    Z2,D2,scale=(-5.0d-1,0.0d0))
    
    !Diagram      0; Contraction 23; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("Z2(e1,f1,m1,n1)+=D2(f1,e1,n1,m1)", &
    Z2,D2,scale=(5.0d-1,0.0d0))
    
    ierr=talsh_tensor_destruct(D2)
    
    ierr=talsh_tensor_construct(E2, C8, (/nvir,nvir,nocc,nocc/), init_val=ZERO)
    
    !Diagram      0; Contraction 24; Tree Level  2; Scaling  2/ 4/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("E2(e1,f1,n1,m1)+=F4(e1,d1)*T2(f1,d1,n1,m1)", &
    E2,F4,T2,scale=(1.0d0,0.0d0))
    
    !ierr=talsh_tensor_destruct(F4)
    
    !Diagram      0; Contraction 25; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("Z2(e1,f1,m1,n1)+=E2(e1,f1,n1,m1)", &
    Z2,E2,scale=(1.0d0,0.0d0))
    
    !Diagram      0; Contraction 26; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("Z2(e1,f1,m1,n1)+=E2(f1,e1,n1,m1)", &
    Z2,E2,scale=(-1.0d0,0.0d0))
    
    ierr=talsh_tensor_destruct(E2)
    
    ierr=talsh_tensor_construct(G2, C8, (/nvir,nvir/), init_val=ZERO)
    
    !Diagram      0; Contraction 27; Tree Level  3; Scaling  4/ 4/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  0/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("G2(f1,d1)+=V7(l1,m2,d1,e2)*T2(e2,f1,l1,m2)", &
    G2,V7,T2,scale=(1.0d0,0.0d0))
    
    !ierr=talsh_tensor_destruct(V7)
    
    ierr=talsh_tensor_construct(I2, C8, (/nvir,nvir,nocc,nocc/), init_val=ZERO)
    
    !Diagram      0; Contraction 28; Tree Level  2; Scaling  2/ 4/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_contract("I2(e1,f1,m1,n1)+=T2(e1,d1,m1,n1)*G2(f1,d1)", &
    I2,T2,G2,scale=(1.0d0,0.0d0))
    
    ierr=talsh_tensor_destruct(G2)
    
    !ierr=talsh_tensor_destruct(T2)
    
    !Diagram      0; Contraction 29; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("Z2(e1,f1,m1,n1)+=I2(e1,f1,m1,n1)", &
    Z2,I2,scale=(5.0d-1,0.0d0))
    
    !Diagram      0; Contraction 30; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("Z2(e1,f1,m1,n1)+=I2(f1,e1,m1,n1)", &
    Z2,I2,scale=(-5.0d-1,0.0d0))
    
    ierr=talsh_tensor_destruct(I2)
    
    !Diagram      0; Contraction 31; Tree Level  1; Scaling  2/ 2/ 0/ 0/ 0/ 0/ 0.1+01; Result_size  2/ 2/ 0/ 0/ 0/ 0/ 0.1D+01
    ierr=talsh_tensor_add("Z2(e1,f1,m1,n1)+=V3(e1,f1,m1,n1)", &
    Z2,V3,scale=(1.0d0,0.0d0))
    
    !ierr=talsh_tensor_destruct(V3)
    
    
end subroutine talsh_tenpi_ccd
